### ISSUE TITLE
Add a price oracle 

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#100]
We need to have a price oracle for spacewalk. How exactly this would look is not yet decided. See the related [notion ticket](https://www.notion.so/satoshipay/Find-price-oracle-for-Spacewalk-a653f0e7cabf48519b154f4d54afba70).

**Comment by cr4pt0** [comment]
#177 
merged 
https://github.com/pendulum-chain/spacewalk/pull/187
