### ISSUE TITLE
Make client recover missed scp messages from network

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#115]
At the moment, the client must always be online to receive SCP messages required to build proof for the stellar oracle. Since we cannot assume that the client is always online, e.g. due to network outages, or even just for upgrading it, we have to have a way to recover missed SCP messages.

There are two options to do so: 
1) Send a `GET_SCP_STATE` message to the overlay network with the missing ledger/slot as parameter, or
2) Look up the SCP messages from a stellar history archive node.

To 1)
- The `GET_SCP_STATE` message works like the `GET_TX_SET` message so that the implementation we already have for fetching the transaction set from the overlay network can be considered for this.
- It is not yet clear what the response for the `GET_SCP_STATE` messages looks like and if it contains only the SCP statement of one validator node or more of them. So the first step would be to do this request once, and check what we get as a result.
- The validators will not hold this data forever and probably prune it according to [this](https://github.com/stellar/stellar-core/blob/ca2fb06059c15442cb4c9a8c89de1a8fc3579a39/docs/stellar-core_example.cfg#L337) setting

To 2)
- stellar-core servers store historical data in archives so that other peers who join the network have the means to catch up
- This is described in more detail in [this](https://github.com/stellar/stellar-core/blob/master/docs/history.md) document
- SCP messages are also a part of this historical data, although this is optional as described at the end of the document
- However, our client can also use this information to find the SCP messages for a given slot if it is missing them
- The data is encoded. The encoding is also explained in the [history document](https://github.com/stellar/stellar-core/blob/master/docs/history.md). An example of an SCP archive can be found [here](http://history.stellar.org/prd/core-live/core_live_002/scp/01/d1/91/scp-01d1917f.xdr.gz).
- The history nodes write to history every 64 ledgers, which means that the archive data is updated every 64 blocks only

This means that depending on how far the slot that we are missing SCP messages for lies behind the current slot, we have to choose either option 1) or 2).

**Comment by web3online** [comment]
This note for the first option:
- The validators will not hold this data forever and probably prune it according to [this](https://github.com/stellar/stellar-core/blob/ca2fb06059c15442cb4c9a8c89de1a8fc3579a39/docs/stellar-core_example.cfg#L337) setting

Does it mean that we should explore the second option over the first option at all?

**Comment by ebma** [comment]
We could just go with option 2) but I would prefer to have both. The reason is that 2) involves many more steps because we first have to find and fetch the appropriate file from an archive node, uncompress and decode it, and filter its data to find the appropriate messages, while for option 1) we 'only' have to send some `GET_SCP_STATE` messages to the overlay network to which we are connected anyways. 
So I would implement the client such that if it notices that it is missing some required SCP messages, it always starts with option 1) and would consider option 2) as the fallback if we did not receive the data we need with option 1).

**Comment by ebma** [comment]
Just as a side note. We identified that stellar-core servers have the [`MAX_SLOTS_TO_REMEMBER`](https://github.com/stellar/stellar-core/blob/ca2fb06059c15442cb4c9a8c89de1a8fc3579a39/docs/stellar-core_example.cfg#L478) parameter which is configurable and determines how many 'old' slots the node keeps around before deleting them. It is set to 12 by default, but we will probably increase it for our SatoshiPay stellar core servers.

**Comment by ebma** [comment]
Closed by #122.
