### ISSUE TITLE
Drop connection after the defined retries and timeouts

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/spacewalk#120]
In the oracle.rs or even the connect.rs example, the log keeps going with _`peeking empty`_ even after the the retry and timeouts are exhausted.
Reported by @cr4pt0 .

Modify stellar-relay [to stop logging this error and  to stop the program completely.](https://github.com/pendulum-chain/spacewalk/blob/8cf9ccd2cad3de34964cc05a894f94f024bc9aad/clients/stellar-relay/src/connection/services.rs#L171) The retry variable should be incremented every time such error happens.

**Comment by cr4pt0** [comment]
Merged
https://github.com/pendulum-chain/spacewalk/pull/142
