### ISSUE TITLE
Improve error handling for conversion traits

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/spacewalk#13]
Let's improve error handling for the traits implemented in the following files:
- `pallets/spacewalk/addres_conv.rs`
- `pallets/spacewalk/currency_conv.rs`
- `pallets/spacewalk/balance_convertsion.rs`

**Comment by gonzamontiel** [comment]
Specifically: throw proper errors when using StaticLookup:
```rust
    fn lookup(key: Self::Source) -> Result<Self::Target, LookupError> {
        Ok(stellar::PublicKey::from_binary(key.into()) as stellar::PublicKey) // throw error if address is not compatible with Stellar
    } 
```

**Comment by ne-manya** [comment]
It's not too clear what we should do here. Both StaticLookup and LookupError come from substrate crates,
so they can not be changed for lookup function to return our own custom errors.
We don't get anything from converting our custom errors to LookupError since LookupError is just empty struct
that doesn't hold value.

**Comment by gonzamontiel** [comment]
> It's not too clear what we should do here. Both StaticLookup and LookupError come from substrate crates, so they can not be changed for lookup function to return our own custom errors. We don't get anything from converting our custom errors to LookupError since LookupError is just empty struct that doesn't hold value.

Okay you're right, then what's left is to re-throw the error from the callers of these functions, to be able to give the user a better error names.

**Comment by ebma** [comment]
Closing this because we don't really need it anymore.
