### ISSUE TITLE
Add rate limiting

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#151]
In order to slowly roll out Pendulum and to make it more secure against attacks, implement some kind of volume limiting.

The general idea is that the total issue volume and the total redeem volume within any 24 hour time window must not exceed that limit.

### How to configure
There are two ways to implement the limit: a) as a configuration parameter, b) as a storage value.
For a) one would require a runtime upgrade to change the limit. For b) one can provide a root extrinsic function that would allow to change the stored value.

Since a) is simpler to implement, I propose that we start with a) in the first version.

### Type
The value itself should be an `Option<BalanceOf<T>>`. If the value is not set, then there is no rate limiting.

### Algorithm
The general idea is to check for every redeem or issue whether the total volume in the last 24hours reached the limit. This requires to store every redeem and issue event in the previous 24 hours and to compute an accumulated value.

Due to time and memory constraints one could simplify and approximate this as follows: define regular 24 hour intervals (e.g., every 24 * 3600 / 12 blocks) and just ensure that within any of these intervals the total volume limit is not exceeded. This requires only two variables: 
* a `counter` that keeps track of the total volume in the current interval
* an `index` that stores the interval number of the last issue/redeem happened

For a new issue/redeem: 
1. check whether the current interval is larger than `index`; if that is the case, reset `counter` to 0 and set `index` to the current interval.
2. Then decline the issue/redeem if `counter` + the volume of the issue/redeem exceeds the limit.
3. Increment `counter` by the volume of the issue/redeem

This approximation is crude as it allows that up to double the volume limit can be moved within a 24 hour window (if it happens around the beginning of a new interval). But at least the actual volume cannot be orders of magnitudes higher.

### Discussion
We might want to keep two separate limits for issue and redeem as it might be better to have loser limits on redeems (might be bad user experience if users have to wait 24 hours in order to execute redeems).

What is the implication for liquidations?

**Comment by cr4pt0** [comment]
@TorstenStueber 
> an index that stores the interval number of the last issue/redeem happened

Does `index` variable means a last `block_number` for current interval?
And if the `current_block_number` will be > `index` then we reset `counter` and set new calculated `block_number` to `index` storage value?

**Comment by TorstenStueber** [comment]
Define a fixed length for the interval, say `interval_length` (e.g. the number of blocks in 24 hours: 24 * 60 * 60 / 12).

Then the **interval index** is `block_number / interval_length` (integer division of course). 

For a new redeem/issue, determine the current interval index and compare with the variable `index`.

If they are the same, then the previous transaction happened in the current interval and `counter` is the accumulated volume of the current interval.

If `index` is less than the current interval, then the previous transaction happened in an earlier interval and `counter` is the accumulated volume of that earlier interval and has no relevance for the current interval anymore, so that it can be reset to 0.

**Comment by ebma** [comment]
I think I would prefer going with option b) from the start since it should not be that much more difficult to implement while changing it from option a) to b) in the future might require more effort. 

I would recommend adding this storage item to the ['security'-crate](https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/security/src/lib.rs) since this crate is used by issue/redeem anyways, and we could consider this rate limiting a security feature anyways.

**Comment by cr4pt0** [comment]
merged
https://github.com/pendulum-chain/spacewalk/pull/154
