### ISSUE TITLE
Add `clippy --fix` to pre-commit script

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#153]
It might be a good idea to add a `clippy --fix` command to the existing pre-commit script. It can automatically apply some best practices to the code, which the CI is likely to complain about anyways.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/153?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber

**Comment by prayagd** [comment]
@ebma Do we need this for the public launch ?

**Comment by ebma** [comment]
No, it's just for our own developer experience. It's not necessary for the product.

**Comment by TorstenStueber** [comment]
@ebma can we move this to the Ready column?

**Comment by TorstenStueber** [comment]
@ebma can we move this to the Ready column?
