### ISSUE TITLE
Add faucet to send test tokens to accounts

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#161]
It would be nice to have a faucet that we can use to top up accounts with testing tokens. Interlay has [something](https://github.com/interlay/interbtc-clients/tree/master/faucet) for that implemented in Rust. We could do the same or implement it elsewhere. Hosting it online might be better so that the user does not have to run an extra service locally.

**Comment by vadaynujra** [comment]
Will be estimated when implementation approach is defined / agreed.

**Comment by prayagd** [comment]
Took a temporary approach to setup a account which product owns and can send tokens if and when needed by the vaults. Should we move this to a different epic?

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/161?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by ebma** [comment]
The implementation approach is still not really defined so it still wouldn't make much sense to estimate it.

**Comment by TorstenStueber** [comment]
@gonzamontiel we worked on a faucet in the past. Can you remember the status? Maybe we can reuse it here.

**Comment by prayagd** [comment]
Adding the repo for reference https://github.com/pendulum-chain/pendulum-faucet

**Comment by gonzamontiel** [comment]
I think it could be reused, it was made with Netlify functions, so you needed to hit the URL with your account. We would need to change the RPC endpoint and revisit the code a bit. But I would say it's ready to use.
