### ISSUE TITLE
Add total volume limit

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#166]
Add another rate limit setting that defines how much total collateral all vaults can lock in total.

**Comment by cr4pt0** [comment]
@TorstenStueber 
According to this #151  we implemented rate limit with configurable interval length . 
Issue/Redeem volume will reset after when interval ends 
So it is enough to specify pretty long interval.

**IntervalLength** Storage
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/redeem/src/lib.rs#L197
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/issue/src/lib.rs#L176-L178

Default interval length is **24hours**
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/redeem/src/lib.rs#L223
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/issue/src/lib.rs#L200-L201

Extrinsic to update rate limit settings : **rate_limit_update**
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/redeem/src/lib.rs#L418-L439
https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/pallets/issue/src/lib.rs#L314-L335
