### ISSUE TITLE
Fix rpc methods not properly exposed

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#202]
The rpc functions for the spacewalk pallets are not properly exposed somehow. Strangely, when querying the supported rpc methods from chain, they are listed.  

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/6690623/212964339-2f5d9cd6-286f-4fb6-bc7e-eaca38509955.png">

But they are not shown in the list and are not callable. 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/6690623/212964514-5c4d1827-825f-402e-a7a0-9026126710b6.png">

So it might be a small configuration issue. This was tested on the `dev/milestone-3` branch.

**Comment by b-yap** [comment]
https://substrate.stackexchange.com/questions/5684/show-custom-rpcs-runtimeapis-in-polkadotjs-ui

**Comment by b-yap** [comment]
https://substrate.stackexchange.com/questions/2210/custom-rpcs-not-decorated

**Comment by b-yap** [comment]
This also means our runtime apis are not exposed too.

**Comment by b-yap** [comment]
First off we have to define our custom rpc. See this example from moonbeam: https://github.com/PureStake/moonbeam/blob/a4af9c65dd936cdeabafe18087c7066ba4152032/tools/generate-rpc-types.ts#L178-L181

See it live in  polkadot.js:  
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam.api.onfinality.io%2Fpublic-ws#/rpc

My guess is that it's officially added in [polkadot-js](https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec) itself.

**Comment by ebma** [comment]
Thanks a lot for your research on this @b-yap. I did not know that this does not happen automagically. But now that I know, I can add them to our type definitions in [pendulum.js ](https://github.com/pendulum-chain/pendulum.js). Since this will happen in another repository and there is nothing else to do in Spacewalk I'm gonna close this ticket.
