### ISSUE TITLE
Change CI jobs and upgrade runner

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#211]
At the moment, our CI jobs fail more even than they pass. In many cases, it is one of the integration tests that fails. We need to take some action here because we of course do not want to have CI jobs that fail all the time.

There are some things we should do:
- Remove the `macOS` job. Currently, the same tasks are executed on both an ubuntu and a macOS machine. We don't need to have both, so we should remove the macOS one.
- Look into how exactly the tests fail. 
   - Since the integration tests pass when run locally, this hints that it is a resource issue of the runner and we can fix it by choosing a more powerful option. This is not free though, the possible options and costs can be found [here](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).
   - It might be however that this is not even related to resources and can be fixed by changing something in the tests. That's why we should have a look at the exact error messages first. 

This issue is about the current `dev/milestone-3` branch and the changes should be added to it so that we can merge it to main once the CI jobs are fixed.

**Comment by b-yap** [comment]
https://github.com/pendulum-chain/spacewalk/pull/237

**Comment by ebma** [comment]
Closed by #237. We did not remove the macos runner but we made the two jobs run sequentially so that they are not issuing stellar transactions for the same account at the same time.
