### ISSUE TITLE
Integration tests design after spacewalk oracle redesign.

### ISSUE THREAD

**Issue by cr4pt0** [pendulum-chain/spacewalk#212]
https://github.com/pendulum-chain/spacewalk/blob/oracle-pallet-redesign-177/clients/vault/tests/vault_integration_tests.rs
All integration tests for vault client failed because we removed spacewalk oracle extrinsic `feed_values`

7 unit tests failed because there is no way to set prices for 
```
const DEFAULT_NATIVE_CURRENCY: CurrencyId = Token(TokenSymbol::PEN);
const DEFAULT_TESTING_CURRENCY: CurrencyId = Token(TokenSymbol::DOT);
const DEFAULT_WRAPPED_CURRENCY: CurrencyId = CurrencyId::AlphaNum4 {
	code: *b"USDC",
	issuer: [
		20, 209, 150, 49, 176, 55, 23, 217, 171, 154, 54, 110, 16, 50, 30, 226, 102, 231, 46, 199,
		108, 171, 97, 144, 240, 161, 51, 109, 72, 34, 159, 139,
	],
};
```

By new design of spacewalk oracle need to rewrite `feed_values` subxt functionality. And there is two approach:
- to feed value to DIA oracle pallet calling `set_updated_coin_infos` extrinsic.
- to configure DIA oracle that way that DIA oracle off_chain worker will do all work by himself. (but there is no prices for 
```
const DEFAULT_WRAPPED_CURRENCY: CurrencyId = CurrencyId::AlphaNum4 {
	code: *b"USDC",
	issuer: [
		20, 209, 150, 49, 176, 55, 23, 217, 171, 154, 54, 110, 16, 50, 30, 226, 102, 231, 46, 199,
		108, 171, 97, 144, 240, 161, 51, 109, 72, 34, 159, 139,
	],
};
```
)

First approach is much easy to implement.
And of course there is no way to configure second option because DIA oracle does not provide tokens about PEN prices.

@erasmus How we are going to solve the issue in production to ask DIA oracle to provide assets for Stellar network for USDC assets.
Or we are going to use price for Stellar USDC from Ethereum blockchain.
For Ethereum USDT there is a price : https://api.diadata.org/v1/assetQuotation/Ethereum/0xdAC17F958D2ee523a2206206994597C13D831ec7
```
{
  "Symbol": "USDT",
  "Name": "Tether USD",
  "Address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  "Blockchain": "Ethereum",
  "Price": 0.9998995784873773,
  "PriceYesterday": 1.0000981459621183,
  "VolumeYesterdayUSD": 711980530.344301,
  "Time": "2023-01-19T13:13:58.986Z",
  "Source": "diadata.org"
}
```
@TorstenStueber @ebma

**Comment by ebma** [comment]
So if I understand correctly, the question is how to feed our custom exchange rates to the DIA oracle pallet. As you described, I guess it is best to call the `set_updated_coin_infos` extrinsic on the DIA pallet. So I would be fine if you do so.

Regarding the second question, I actually also don't know how we want to get the prices for the stellar assets we want to bridge. Someone has to feed them to the oracle obviously but I don't know based on what we would calculate the price.
