### ISSUE TITLE
Refactor DIA implementation

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#234]
There are some things that are not really clean about the code introduced when adding the DIA oracle yet. 

We should:
- [x] Deduplicate all the mock structures that were introduced and added to other pallets. 
Due to some issue with the `thread_local` implementation we had to copy the same mock code to multiple pallets. This is not ideal of course and we should try to get rid of it. Maybe an implementation similar to [this](https://github.com/pendulum-chain/spacewalk/blob/521b97187a271879d8e921b4d7d4da89493c8fbf/testchain/runtime/src/benchmark_utils.rs) one can help and make us able to declare all this code in just one place, sharing it throughout the repository.
- [x] ~~Improve and deduplicate the DiaOracleKeyConvertor. Right now, the DiaOracleKeyConvertor does not take the issuer of stellar assets into account. We should think about changing that. We should find a way to translate between Stellar assets and DIA identifiers bi-directionally meaning that a Stellar asset (issuer + code) is uniquely defined by a DIA asset and vice versa. For this to work, we might also have to touch the dia-batching-server implementation because this responds with the prices for DIA assets.~~ Will be addressed in #396 

Follow-up ticket to the changes made in #187.

**Comment by TorstenStueber** [comment]
@ebma I think that we should not consider one price per code as the same codes could mean something completely different for different issuers. This is unlikely but it is probably good to keep it conceptually separate.

At one point the Stellar asset needs to be translated to into the DIA namespace. Not sure where the perfect point to do this is, but we should make sure that we don't translate full Stellar asset identifiers to only the asset name and that then only to the DIA namespace.

**Comment by ebma** [comment]
Agreed and updated the ticket.

**Comment by ebma** [comment]
I created a follow-up ticket for the second task of this issue. The refactoring of the mock code already took quite some effort so it makes sense to split this issue into two separate tasks instead of combining them in a single PR.
