### ISSUE TITLE
Potential `tx_bad_seq` when submitting Stellar Transaction

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/spacewalk#239]
A `tx_bad_seq` happens when user submits a stellar transaction with:
*  a sequence number lower than in the account's `sequence` field
* a sequence number is two points greater than in the account's `sequence` field.   
e.g. The account's `sequence` = 123456**7** and the transaction sequence number = 123456**9**

It  randomly happened, as observed in [1 CI Run](https://github.com/pendulum-chain/spacewalk/actions/runs/4044864074/jobs/6972097491#step:11:2193).

This is also thoroughly explored in a [certik report](https://skyharbor.certik.com/shared-report/incremental/18dda774-6b83-4d68-a396-c0882da215c5?findingIndex=1674739325615).

**Comment by b-yap** [comment]
https://github.com/pendulum-chain/spacewalk/pull/241

**Comment by ebma** [comment]
Closed by #241
