### ISSUE TITLE
Check the amount of Stellar transactions in redeem/replace requests

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#243]
At the moment, we don't check if the Stellar transaction used in redeem and replace requests contains a payment with the defined amount to the defined destination. We only check if the transaction was successfully executed on Stellar and if it contains the appropriate memo. 

We should use the function declared in the currency crate to extract the amount and check it.

**Comment by cr4pt0** [comment]
@ebma 
What is the best way to validate amount and what todo next with vault if the expected amount greater or less than actual transferred  amount?

**Comment by ebma** [comment]
Did you figure this out or do you still need my input for this @cr4pt0 ?

**Comment by cr4pt0** [comment]
> Did you figure this out or do you still need my input for this @cr4pt0 ?

Thanks. Everything is clear. in progress.

**Comment by cr4pt0** [comment]
Merged
https://github.com/pendulum-chain/spacewalk/pull/250
