### ISSUE TITLE
Change handling of open requests

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#244]
We should change the behavior of how we handle the open redeem and replace requests in ` /clients/vault/src/execution.rs`. When handling the request, at the moment the first step removes it from the collection of open requests. The request handling could fail however. Since we removed it from the queue of open requests it will not get retried. 
We should change this to either only remove it upon successful execution, or we re-add it to the queue if it failed.

**Comment by b-yap** [comment]
https://github.com/pendulum-chain/spacewalk/pull/245
