### ISSUE TITLE
Fix 'informational' issues (audit recommendations)

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#257]
There are some very minor things brought up in the audit that we might want to fix. The following checklist only includes the item ID; the description and details can be found by looking at the audit report.
- [x] TYP-01 Confusing Variable Naming
- [x] SYS-03 Unnecessary Variable
- [x] STA-02 Lack of Validation for `destination_adress` on `send_payment_to_address()`
- [x] STA-01  Code duplication
- [x] SRW-01 Usage of hard-coded string
- [x] SRC-01 Unused Methods and Storage
- [x] PRO-01 Unhandled Error
- [x] PAE-02 Usage of magic numbers
- [x] PAE-01 Unnecessary `Result<>` Return Type
- [x] LIT-04 Reduce using `unwrap()` and `expect()` in Production Codebase
- [x] LIT-03 Panic can happen between correlated storage modifications
- [x] LII-01 Inconsistent match expression
- [x] LIE-04 Mismatch in variable name and pallet
- [x] LIL-01 Dead Code in `execute_replace()`
- [x] IMP-01 Same Behavior Defined for different conditions
- [x] EXC-01 Missing information in logging message
- [x] CLI-03 Incorrect error type thrown
- [x] CLI-02 Typos
- [x] CLI-01 Confusion function naming
- [ ] #417
- [x] 4FC-04 Logic should be moved to a separate function - refactoring
- [x] 4FC-03 Unused errors
- [x] 4FC-02 Inconsistent comments

Since the changes are so minor, it's okay to include all of them in one branch and one Pull Request. But each of them should at least be addressed in a separate commit with a proper name, also mentioning the **ID** in the name so that it's easier to track the changes.

additional:

- [ ] GLOBAL-05 Unneceessary Off-Chain User Protection Mechanism
- [x] LI5-02 TryFrom `CurrencyId` implementations Contain Repeated Code
- [x] LIH-03 Values Length Not Validated in `feed_values` Function

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/257?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber

**Comment by b-yap** [comment]
EXC-01 -  Missing information in logging message
was completed by https://github.com/pendulum-chain/spacewalk/pull/377

**Comment by b-yap** [comment]
4FC-04 Logic should be moved to a separate function - refactoring -> https://github.com/pendulum-chain/spacewalk/pull/388

**Comment by b-yap** [comment]
could not find the ff. in skyharbor.certik:
*  LIL-01 Dead Code in `execute_replace()`
*  LIT-03 Panic can happen between correlated storage modifications

**Comment by ebma** [comment]
Oh right, that's weird. I also can't find them to be honest 😅 
@b-yap can you check and compare the informational issues that are listed on page 46 ff. to the informational issues that are listed in the description of this ticket and add any that's missing? For example, I can see that 'LIH-02 Values Length Not Validated In feed_values Function' is also not included and there might be others. I'll attach the final report here so that it's unambiguous which report we are talking about. 
[REP-final-20230303T193754Z.pdf](https://github.com/pendulum-chain/spacewalk/files/12486434/REP-final-20230303T193754Z.pdf)

**Comment by b-yap** [comment]
LI5-02 TryFrom CurrencyId implementations Contain Repeated Code 
was completed by https://github.com/pendulum-chain/spacewalk/pull/264 (see 4th commit)

**Comment by b-yap** [comment]
https://github.com/pendulum-chain/spacewalk/pull/390 covers:
* IMP-01 Same Behavior Defined for different conditions
* LIE-04 Mismatch in variable name and pallet
* 4FC-02 Inconsistent comments
* PRO-01 Unhandled Error
* LIH-03 Values Length Not Validated in feed_values Function
* CLI-01 Confusion function naming
* CLI-03 Incorrect error type thrown

**Comment by b-yap** [comment]
@ebma one of the concerns of  _4FC-05 Commented out code_ are
https://github.com/pendulum-chain/spacewalk/blob/ad68c16f55141357d14df66d40717b42d089c96c/clients/vault/src/system.rs#L718-L720

and
https://github.com/pendulum-chain/spacewalk/blob/ad68c16f55141357d14df66d40717b42d089c96c/clients/vault/src/system.rs#L660
Do you know what to do here, or is a separate ticket needed to address this?

**Comment by b-yap** [comment]
4FC-05 Commented out code
   -  some of them do not exist anymore:
* https://github.com/pendulum-chain/spacewalk/blob/53050f52be1f941ebe1d56d14088f0d515ada474/clients/vault/src/oracle/agent.rs#L219
*  https://github.com/pendulum-chain/spacewalk/blob/53050f52be1f941ebe1d56d14088f0d515ada474/clients/runtime/src/types.rs#L77
* https://github.com/pendulum-chain/spacewalk/blob/53050f52be1f941ebe1d56d14088f0d515ada474/primitives/src/lib.rs#L697-L700

**Comment by ebma** [comment]
The related ticket already exists. It's [this](https://github.com/pendulum-chain/spacewalk/issues/161) one. I would keep the comments until we actually implemented the ticket about the faucets. If there is no other commented out code besides these, then there is nothing to do IMO.

**Comment by b-yap** [comment]
LIT-04 Reduce using unwrap() and expect() in Production Codebase
does not exist anymore:
* https://github.com/pendulum-chain/spacewalk/blob/b5307e9c1e805bafe4546e661df056c96548a878/pallets/stellar-relay/src/lib.rs#L619
* https://github.com/pendulum-chain/spacewalk/blob/b5307e9c1e805bafe4546e661df056c96548a878/pallets/stellar-relay/src/lib.rs#L654

**Comment by b-yap** [comment]
#393 covers:
  * STA-01 Code duplication
  * SRC-01 Unused Methods and Storage
  * 4FC-05 Commented out code
  * LII-01 Inconsistent match expression
  * LIT-04 Reduce using unwrap() and expect() in Production Codebase
  * TYP-01 Confusing Variable Naming

**Comment by b-yap** [comment]
GLOBAL-05 Unneceessary Off-Chain User Protection Mechanism
> The mechanism described (reported below) in the document Spacewalk Specification (Audit) in the section security_consideration/theft_reporting adds unnecessary off-chain complexity to the bridging protocol that can be avoided without having an impact on the protocol design.
> "We also don’t need theft reporting because all cases are covered except for one scenario: the user sends a payment to a vault as part of an issue request, but the vault does not call the executeIssue() extrinsic." "To protect the user in this scenario, we can implement an extra mechanism to the web app that allows the user to register new issue request

@ebma correct me if I'm wrong: the off-chain mechanism mentioned here is:
https://github.com/pendulum-chain/spacewalk/blob/5fc74e08ebdcf334529ee9fb73fd2c29bdc10f7a/pallets/vault-registry/src/lib.rs#L780
?

**Comment by ebma** [comment]
@b-yap yes, I think it is. I'm curious however, because I think we cannot just remove that line. I think there is no other check for undercollateralized vaults. What I say in the quote about no need for theft reporting is irrelevant here, because 
```
 let call = Call::report_undercollateralized_vault { vault_id: vault }; 
```
is not reporting for theft on Stellar, but it's reporting about undercollateralized vaults. 

@b-yap can you check whether the current implementation checks and punishes undercollateralized vaults in another place than the line you linked to?

**Comment by ebma** [comment]
@b-yap pinging you again about the question before, before we close this ticket.

**Comment by ebma** [comment]
> I do not see report_undercollaterized_vault() being called anywhere else besides an unsigned extrinsic call.

Can you share a link to where it's being called?

**Comment by b-yap** [comment]
https://github.com/pendulum-chain/spacewalk/blob/5fc74e08ebdcf334529ee9fb73fd2c29bdc10f7a/pallets/vault-registry/src/lib.rs#L128C6-L151
i meant when validating an extrinsic call.

**Comment by ebma** [comment]
I still think GLOBAL-05 is reported wrongly and they misunderstood some part of the logic. Referring to what they say in their comment, I think they misunderstand theft reporting as reporting undercollateralized vaults. Theft reporting was about reporting vaults that transfer the assets they hold somewhere else on Stellar. And we don't care about that. But undercollateralized vaults are still important for us. Thus, GLOBAL-05 is nothing we need to change. And since it's the last remaining issue of this ticket, we can close it.
