### ISSUE TITLE
Make remote resource locators configurable

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#261]
We should make some of our hard-coded URLs configurable so that in case some endpoint goes down, the vault operator has the chance to react to this and change the endpoint addresses without having to recompile the whole codebase.
The related audit item is `ORA-01`.

**Comment by erasmus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/261?planning-poker) with Zenhub @ebma @TorstenStueber

**Comment by erasmus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/261?planning-poker) with Zenhub @ashneverdawn
