### ISSUE TITLE
Add optimizations (audit recommendations)

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#263]
Some optimizations were proposed by the auditors. The following checklist only includes the item ID; the description and details can be found by looking at the audit report.
- [x] SYS-04 Double Iterations can be merged into a single one
- [x] SRW-02 `limit` parameter type optimization
- [x] RPC-01 Closure usage could simplify the codebase
- [x] PRO-02 Return Type Could be an `Option`
- [x] LIV-01 Duplicated Helper Function Call
- [x] LIT-05 Double `for` Loop could be merged
- [x] LIP-04 Potential Unnecessary Computations
- [x] LIP-03 Redundant Condition Check
- [x] LII-02 Duplicated Condition Check
- [x] IMP-02 Empty Strings as prefixes
- [x] HOR-01 Unnecessary Variable cloning
- [x] EXC-02 Double `filter()` calls can be reduced with `filter_map()` 
- [x] 4FC-06 Loops optimizations with iterators

Since most optimizations are minor, it's okay to include all of them in one branch and one Pull Request. But each of them should at least be addressed in a separate commit with a proper name, also mentioning the ID in the name so that it's easier to track the changes.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/263?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber
