### ISSUE TITLE
Rename type `Ledger` to `Slot`

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/spacewalk#277]
As [mentioned](https://github.com/pendulum-chain/spacewalk/pull/276#discussion_r1118595357) by @ebma :
> While 'Ledger' is used to describe a block in the Stellar world, the term 'slot' is rather used in the SCP consensus paper etc. But at the end of the day it boils down to the same thing when it comes to the number we store for a ledger and a slot. For one transaction x the slot and ledger will be equal to each other.

> Thus, I would prefer if we find a better way for describing this. If I remember correctly we already have a type for Slot, maybe we could just re-use that one.

**Comment by b-yap** [comment]
@ebma  
While I'm all about Slot == Ledger, there's a difference of datatypes.

[Slot is defined as u64](https://github.com/pendulum-chain/spacewalk/blob/6c272183f3a9a766c90adc665a0f2e0929903ccf/clients/vault/src/oracle/types.rs#L10): 
```rust
pub type Slot = Uint64;
```
and [Ledger is u32](https://github.com/pendulum-chain/spacewalk/blob/6c272183f3a9a766c90adc665a0f2e0929903ccf/clients/wallet/src/lib.rs#L12):
```rust
pub type Ledger = u32;
``` 

Shall we address where to handle the conversion from Ledger to Slot? And also, where to define the `Slot` type to make it easily accessible?

Can we actually cleanup the following:
* [`let slot = transaction.ledger as Slot;`](https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/clients/vault/src/execution.rs#L274) 
* [`let slot_index: u32 = slot.try_into().unwrap();` in impl.rs](https://github.com/pendulum-chain/spacewalk/blob/6c272183f3a9a766c90adc665a0f2e0929903ccf/clients/vault/src/oracle/storage/impls.rs#L419)
* [`let slot = response.ledger as u64;`](https://github.com/pendulum-chain/spacewalk/blob/6c272183f3a9a766c90adc665a0f2e0929903ccf/clients/vault/tests/vault_integration_tests.rs#L110)
* [`let slot_index: u32 = slot.try_into().unwrap();` in proof_builder.rs](https://github.com/pendulum-chain/spacewalk/blob/dev/milestone-3/clients/vault/src/oracle/collector/proof_builder.rs#L238)

---

> **_'Ledger' is used to describe a block in the Stellar world,_**  

   * Is it correct to assume,  that the '**Ledger**' term will strictly be used only when interacting with the `stellar-substrate-sdk`  lib? 
  
> **_the term 'slot' is rather used in the SCP consensus paper_**  
   * Is it correct to assume, that the '**Slot**' term will strictly be used only when interacting with the `stellar-relay-lib` crate?

**Comment by prayagd** [comment]
@b-yap can i icebox this if not urgent?

**Comment by TorstenStueber** [comment]
(also @ebma: still relevant?)

**Comment by ebma** [comment]
This is just some minor refactoring and not super urgent. I'd say it's fine to move it to the icebox but not close it.

**Comment by TorstenStueber** [comment]
Okay, moved to Icebox.
