### ISSUE TITLE
Fix untracked amount transferred

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#281]
There is a scenario in which the vault is able to gain more funds with the `mint_tokens_for_reimbursed_redeem` function than it should be able to. The reason is that when cancelling a redeem, we use the `vault_registry::transfer_funds_saturated()` function to reimburse the user. Since it is 'saturated' this function will try to transfer the target amount, or less if not enough funds are available. The problem is that we don't store information about the amount that is actually transferred. In case that this amount is less than originally intended, the vault operator might be able to gain more funds than he lost when he reimburses the redeem.

To solve it we need to store information about the actually transferred amount, ie. the return value of the `vault_registry::transfer_funds_saturated()` function call and use it in the `mint_tokens_for_reimbursed_redeem` function.

The related audit ticket is `LI7-04`

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/281?planning-poker) with Zenhub @ebma @vadaynujra @b-yap

**Comment by vadaynujra** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/281?planning-poker) with Zenhub @TorstenStueber

**Comment by vadaynujra** [comment]
@ebma does this need to be fixed for the Pendulum launch and so needs to be implemented to Amplitude first?

**Comment by vadaynujra** [comment]
@ebma I noticed that this has been in Review / QA for quite some time. How can this be completed?
