### ISSUE TITLE
Create basic structure

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#3]
This respository contains
* one or more pallet (containing the main artifact of this repository)
  * `pallets`
* a test standalone chain
  * `testchain`
  * use the default template for standalone chains
  * add the spacewalk pallet(s)
    * as a local reference

**Comment by ebma** [comment]
I created the structure and force-pushed to the main branch to get rid of the old files.
The contents of the spacewalk pallet and testchain directory are based on the latest [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template) but I changed the Cargo.toml of the spacewalk pallet and renamed the references in the testchain runtime.
