### ISSUE TITLE
Register RPC methods to polkadot.js

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#303]
In order to make our RPC methods callable from within polkadot.js we need to submit a PR with appropriate changes to them. Otherwise, the RPC methods are available but not easily callable without code.

Edit: This can be considered a follow-up to https://github.com/pendulum-chain/spacewalk/issues/202 issue

**Comment by ebma** [comment]
This can be considered a follow-up to [this](https://github.com/pendulum-chain/spacewalk/issues/202) issue.

**Comment by vadaynujra** [comment]
@ebma is this required to be completed for the Pendulum launch?

**Comment by ebma** [comment]
@vadaynujra no, it's just for our own developer experience again.

**Comment by vadaynujra** [comment]
@ebma what would this enable / provide for developers, in the context of Spacewalk?

**Comment by ebma** [comment]
Let's say you want to convert prices with our on-chain price info. You would be able to use these RPC methods to convert the price of an amount between two assets easily. 
Or let's say you are a vault provider and want to know your current collateral threshold, ie. you want to see how much collateral you provide for the assets you hold (e.g. to check that you are still above our defined thresholds like 160%, etc.), then you can also use an RPC method to query that for your vault.

**Comment by vadaynujra** [comment]
Understood, thank you.

**Comment by ebma** [comment]
No.

**Comment by vadaynujra** [comment]
How would the vaults know their leverage / thresholds at a point in time, based on the current functionality @ebma ?

**Comment by ebma** [comment]
This info is exposed by the vault metrics. When you as a vault operator start the vault client you'll see that the vault exposes metrics at a local port. This is basically a web page you can access that will show you all relevant stats.

**Comment by ebma** [comment]
But you would have to check each vault's metrics page separately, whereas with this function you could just query the relevant stats for the vault you are interested in by passing the respective account info.

**Comment by ebma** [comment]
The [pull request](https://github.com/polkadot-js/apps/pull/9855) was created on the upstream repo and is waiting for approval.

**Comment by ebma** [comment]
The [PR](https://github.com/polkadot-js/apps/pull/9855) was merged and the RPC methods are available on polkadot.js now.
