### ISSUE TITLE
Fix increasing resource consumption of vault client

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#309]
Apparently running the vault client for some period of time on our infrastructure makes it break because it starts consuming too many resources. This happened on t3.micro machines with 1GB of RAM. We should check which values are not properly pruned and cause the memory consumption to increase linearly. 

One thing that probably causes this is an incomplete implementation of the maps for storing transaction sets and scp envelopes. The `EnvelopesMap` and `TxSetMap` are defined as [VecDeques](https://github.com/pendulum-chain/spacewalk/blob/0d9e1f4fa7bf300d1c5007bdc0439f491e9e979b/clients/vault/src/oracle/types.rs#L25-L26) and a custom `LifoMap` trait was implemented for easier getters/setters. The idea was to limit these VecDeques in their size so that the last/oldest item is dropped when a new item is added that exceeds the defined limit. This is not implemented at the moment though and might be the cause of the ever-increasing resource consumption. There is a constant defined [here](https://github.com/pendulum-chain/spacewalk/blob/0d9e1f4fa7bf300d1c5007bdc0439f491e9e979b/clients/vault/src/oracle/constants.rs#L10) but it's not used where it needs to be.

We should: 
- [ ] Rename `LifoMap` to `LimitedFifoMap` because we want to do 'first in first out' actually
- [ ] Turn `LimitedFifoMap` from a trait into a struct. The problem is that we want to define the maximum number of items when instantiating it and we need to access that value for our helper methods so we cannot use a trait. 
- [ ] Instantiate these maps with reasonable limits. Should be at least 200 because when falling back to an archive these contain 200 SCP messages and choosing a smaller limit would drop some potentially important SCP messages from archive files.

The struct can look roughly as follows
```
pub struct LimitedFifoMap<T,K> {
  limit: usize
  queue: VecDeque<T,K>
}

impl<T, K> LimitedFifoMap<(K, T)>
where
	K: PartialEq,
{
     fn new() {
         let default_limit = ...
         Self { }
     }

     fn new_with_limit(){}

      // ...  + the existing helpers on `LifoMap`
     // but accommodating for the limit parameter we have
      fn set_with_key(&mut self, key: K, value: T) {
		// If the key already exists, remove it first
		self.queue.remove_with_key(&key);

                if self.queue.length == limit {
                   // remove first element in queue
                   self.queue.pop_front();
                }

		self.queue.push_back((key, value));
	}
}
```

### Checking the resource consumption
To be able to judge whether the resource consumption was 'fixed' we should check how much RAM the vault client consumes when being run for some time. This should be checked before adding these changes and after. We would expect that the RAM usage of the vault client now saturates at a maximum (when the SCP maps are filled). Thus, when checking the 'after'-implementation, we first have to wait until the maps are filled and can then judge if the RAM usage continues growing.
I would suggest doing the following for the before/after comparison:
1) Run the vault client for two hours
2) Check the resource consumption after one and two hours. (For this, simply check the RAM usage of the process in your system monitor)

Repeat steps 1) and 2) with the new implementation. We would expect that the RAM usage after one hour is very close to the RAM usage after two hours. If that's the case we can consider this ticket completed. Consider adding your measured values to this ticket so they can be used for reference.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/309?planning-poker) with Zenhub @ebma @TorstenStueber

**Comment by vadaynujra** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/309?planning-poker) with Zenhub @ashneverdawn

**Comment by TorstenStueber** [comment]
@ebma should we not make this a research ticket instead to investigate where the memory leaks happen? I suppose that there are some tools available for Rust programs.

**Comment by ebma** [comment]
I am pretty sure that the increased resource consumption is caused by the maps for storing Stellar transaction sets and scp messages which just continue filling without ever being pruned. This is a problem that has to be fixed anyways because I originally imagined the maps to have limits of eg. 200 elements to prevent this from happening. It somehow slipped my radar that this was never implemented like that. 
I'll add more TODO items to the description to check before and after the implementation, if the resource consumption stabilized, if that's not the case we can create another ticket to investigate further.
