### ISSUE TITLE
Include assets USDC, BRL, TZS and XLM

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/spacewalk#311]
Allow stellar assets USDC, BRL, TZS to be bridged (Amplitude and Pendulum).

Edit 1: 
Add the respective asset to the supported oracle keys in the oracle pallet: XLM, BRL, TZS, USDC
Add the currency to the supported currencies in the DIA oracle pallet
Add the below collateralisation parameters for each asset:
Asset | COL | Premium Redeem Factor | Secure Collateralisation Factor | Liquidation Factor 
-- | -- | -- | -- | -- 
USDC | KSM | 140% | 160% | 125% 
TZS | KSM |140% | 160% | 125% 
BRL | KSM | 140% | 160% | 125% 
XLM | KSM | 140% | 160% | 125% 

Edit 2: 
Asset details: 
- [USDC](https://stellar.expert/explorer/public/asset/USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN-1): GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
- [BRL](https://stellar.expert/explorer/public/asset/BRL-GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP-1): GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP
- [TZS](https://stellar.expert/explorer/public/asset/TZS-GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO-1): GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO

## Technical details
To add collateralization parameters for these assets you need to transform the public key of each issuer to the 32-byte representation (as this is what we store on-chain). To do that, you can:
- go to [this](https://npm.runkit.com/playground) node.js playground,
- and paste the following code into it:
```
var StellarSDK = require('stellar-sdk');

var address = "GABDC..."; // TODO change me to the issuer public key
let keypair;
if (StellarSDK.StrKey.isValidEd25519PublicKey(address)) {
	keypair = StellarSDK.Keypair.fromPublicKey(address);
} else if (address.startsWith('0x') && address.length === 66) {
	let pubKey = StellarSDK.StrKey.encodeEd25519PublicKey(Buffer.from(address.slice(2), 'hex'));
	keypair = StellarSDK.Keypair.fromPublicKey(pubKey);
} else {
	console.error("Invalid address format")
}

console.log("ED25519:", keypair.publicKey());	
console.log("hexa:", "0x" + keypair.rawPublicKey().toString('hex'));
```
you can then use the hexadecimal representation of the raw public key when building the extrinsics.

**Comment by ebma** [comment]
What is this about? This should not require any technical changes, we just need to have the collateralization parameters which should be set by product team which are then set for the pallets with a root user transaction.

**Comment by RustNinja** [comment]
Additionally to collateralization parameters we need to specify via root transaction the required currency id to oracle pallet.

**Comment by vadaynujra** [comment]
Added in the details @ebma and @RustNinja.

**Comment by ebma** [comment]
The issuer/public keys for the Stellar assets are missing. Like this it's ambiguous and I am not able to correctly identify who the issuer is. Please tell me the exact issuer for each asset. You can have a look [here](https://resources.stellar.org/anchors?assets=MXN).

**Comment by vadaynujra** [comment]
@ebma added issuer public keys along with source.

**Comment by ebma** [comment]
@vadaynujra how come it has 'MXN' in the table but for issuers you put `TZS'? Which asset do you want to include?

**Comment by vadaynujra** [comment]
TZS has replaced MXN. Updated above @ebma

**Comment by vadaynujra** [comment]
@ebma thanks for bringing up and assuming you're suggesting to change them in a way that they would become less risky for the vault, I think it's a good idea especially the 110% liquidation factor. Can you share the current values for Interlay for their BTC-DOT pair (I think they now have other collaterals as well)? Should it be higher than for DOT-Stablecoin pair?

**Comment by ebma** [comment]
Kintsugi:
Asset | COL | Premium Redeem Factor | Secure Collateralisation Factor | Liquidation Factor 
-- | -- | -- | -- | -- 
KBTC | KSM | 145% | 160% | 130% 

Interlay:
Asset | COL | Premium Redeem Factor | Secure Collateralisation Factor | Liquidation Factor 
-- | -- | -- | -- | -- 
IBTC | DOT | 140% | 155% | 125%

**Comment by vadaynujra** [comment]
Likelihood will be based on past volatility of the pair and from my observation DOT-XLM has been less volatile than a DOT-Stablecoin pair. Let's be conservative here and go with already tried / tested values by Interlay. Updated the ticket above.
