### ISSUE TITLE
Use Stellar fee statistics to derive transaction fee

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#312]
## Context 

The vault client currently always uses the same hardcoded fee parameter for creating payment transactions on Stellar. However, at times with heavy load on the Stellar network it might make sense to choose this fee based on the current network statistics. There is an endpoint we can query this fee data from. It's a simple GET request to [this](https://horizon.stellar.org/fee_stats) URL (different for testnet and mainnet of course).

## TODO

Change the vault client so that it uses a fee for Stellar transactions based on the current fee statistics. To do this,
- Poll the fee statistics from https://horizon.stellar.org/fee_stats every 10 minutes
- Use the `p90` field of `fee_charged` as the fee per operation instead of the [DEFAULT_STROOP_FEE_PER_OPERATION](https://github.com/pendulum-chain/spacewalk/blob/a5cc81ececb9a464fc8caa12c191eeaecf453c4b/clients/wallet/src/mock.rs#L25)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/312?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
I think we should refine this ticket before estimating it.

How would we do this? Query the URL in regular intervals (say, every ten minutes) to define the current fees? Which fee would we choose? There are two types of statistics behind the endpoint: the actual fees paid (with percentiles) and the maximum fee a transaction specified to be willing to pay (also with different percentiles).

I assume that will only consider `fee_charged`. However, what percentile shall we choose? p95? p99?

**Comment by ebma** [comment]
Good question. I'd query every 5 to 10 minutes, consider `fee_charged`, and maybe using the value for `p80` is enough? Doesn't need to be perfect, and above `p90` could get unnecessarily expensive for the vault.

**Comment by TorstenStueber** [comment]
I think we should at least go for `p90`. The example I saw indicate that the `fee_charged` does not get too much out of hand (opposed to `max_fee`) and I think we should lower the risk that even with many retries the vault client fails to submit a transaction.

**Comment by ebma** [comment]
Alright, so we agree on:
- Use the `p90` field of `fee_charged`
- Poll data every 10 minutes

**Comment by TorstenStueber** [comment]
Yes, agreed! Thanks

**Comment by TorstenStueber** [comment]
@ebma shall we move this ticket to icebox?

**Comment by ebma** [comment]
I think we should rather move it to 'ready' and work on it soon. While working on the testing service for Spacewalk it became apparent that Stellar transaction fees can grow quite a lot in rush hours.

**Comment by TorstenStueber** [comment]
Okay, then it is quite important. Do you consider the description of this ticket complete? I assume that this logic will only reside in the vault client.

**Comment by ebma** [comment]
I updated the description.

**Comment by prayagd** [comment]
Updating the priority to High
