### ISSUE TITLE
Retry transaction submission in integration tests

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#313]
Currently, the integration tests might fail if they are executed on two machines roughly at the same time (eg when you execute them on your local machine and in some CI job). The reason is that the hard-coded testing account is used in the integration tests to submit transactions to the Stellar network, which might throw a `tx_bad_seq` error if two submissions happen simultaneously on two jobs. To mitigate this timing issue, we can just make the integration tests retry the submission in case they fail.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/313?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber
