### ISSUE TITLE
Make redeem() accepts Stellar encoded addresses

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/spacewalk#33]
Change the signature of 
```
pub fn redeem(
	origin: OriginFor<T>,
	asset_code: Vec<u8>,
	asset_issuer: Vec<u8>,
	amount: BalanceOf<T>,
	stellar_vault_pubkey: [u8; 32],
)

```
to
```
pub fn redeem(
	origin: OriginFor<T>,
	asset_code: Vec<u8>,
	asset_issuer: Vec<u8>,
	amount: BalanceOf<T>,
	stellar_vault_pubkey: Vec<u8>,
)
```

so `stellar_vault_pubkey` can be a Stellar encoded address.

Furthermore, accept also Stellar encoded account ids for `asset_issuer` (currently it only accepts a string containing a hexadecimal encoding of the binary account id).

Inside the function, detect this case and transform it to an `AccountId` before executing the redeem.

**Comment by TorstenStueber** [comment]
The Stellar encoding of an account id can be decoded by just using the trait [`IntoAccountId`](https://github.com/pendulum-chain/substrate-stellar-sdk/#intoaccountid) from the stellar-sdk. It accepts a string-like type of the Stellar encoded string.

FYI: The Stellar encoding of strings is explained [here](https://stellar.stackexchange.com/a/261). It is very different from the hexadecimal encoding of the binary key.

**Comment by ebma** [comment]
It might be that `asset_issuer` already accepts a String public key, maybe double check before changing that in code.

**Comment by b-yap** [comment]
@gonzamontiel  does this include the `Redeem` event?  both the `stellar_user_id and `stellar_vault_id` ?

currently it's 
```
Redeem {
	asset_code: Vec<u8>,
	asset_issuer: Vec<u8>,
	stellar_user_id: [u8; 32],
	stellar_vault_id: [u8; 32],
	amount: BalanceOf<T>,
},
```
or just leave it as `[u8;32]` ?

**Comment by gonzamontiel** [comment]
So it really depends, the events are taken by the vault, and we will probably need to change also some logic there if we change that value. I think the main point of the ticket is to make it easier for the user while calling the extrinsic. So I wouldn't modify the Event.
