### ISSUE TITLE
Add handling for non-recoverable Stellar submission errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#340]
This is related to #315. 

We need to define what we want to do in case we encounter a non-recoverable Stellar submission error. 
There are some options to approach this:

1. automatically try to recreate and resubmit the transaction without interrupting the flow. 
   - eg when we encounter a `tx_bad_seq` error, we could create a new transaction with the same details (operations, destination, etc) but use a new sequence number and automatically resubmit that. This would only work in some cases though, since if for example the transaction is rejected because the accounts balance is too low, automated handling of this is impossible (as it requires user actions). Also, this might lead to unwanted side effects because recreating a new creation automatically could lead to double payments if done wrong.
1. do not automatically try to create a 'valid' transaction but pass the non-recoverable error to the calling code and log an error message. This approach does not introduce any unwanted side effects but also does not fully solve the situation. For some operations like the account balance of the vault operators account being too low, an action by the vault operator would be required.

Both approaches have their disadvantages. Option 2) with not automatically treating 'non-recoverable' errors is preferrable to prevent double payments, but what do we want to do instead? How would we tell the vault operator what's wrong?

Maybe we should list all non-recoverable errors that can happen and that decide individually how we want to approach each of them.

**Comment by ebma** [comment]
@b-yap @TorstenStueber any opinions on how we should handle them? Let's discuss this here.

**Comment by b-yap** [comment]
@ebma 

I have one update: about the [return type](https://github.com/pendulum-chain/spacewalk/pull/339/files#diff-3d26183721b4b5f82780cd20903298deddbae94cc200ae06e529265f6d2704c7R196) for the method that handles resubmitting transactions from local storage (it's in [PR 339](https://github.com/pendulum-chain/spacewalk/pull/339)):
```rust 
/// Submits transactions found in the wallet's cache to Stellar.
/// Returns a tuple: (list of txs successfully submitted, list of errors of txs not resubmitted)
pub async fn resubmit_transactions_from_cache(
&self,
) -> Vec<oneshot::Receiver<Result<TransactionResponse, Error>>> {
let _ = self.transaction_submission_lock.lock().await;
let horizon_client = Client::new();

let mut return_val = vec![];

let mut collect_errors = |errors: Vec<Error>| {
	for error in errors {
		let (sender, receiver) = oneshot::channel();
		return_val.push(receiver);

		if let Err(e) = sender.send(Err(error)) {
			tracing::error!("failed to send error to list: {e:?}");
		}
	}
};

let envs = match self.cache.get_tx_envelopes() {
	Ok((envs, errors)) => {
		collect_errors(errors);
		envs
	},
	Err(errors) => {
		collect_errors(errors);
		return return_val
	},
};

let me = Arc::new(self.clone());
for env in envs.into_iter() {
	let me_clone = Arc::clone(&me);
	let horizon_clone = horizon_client.clone();

	let (sender, receiver) = oneshot::channel();
	return_val.push(receiver);

	tokio::spawn(async move {
		if let Err(e) = sender.send(me_clone.submit_transaction(env, horizon_clone).await) {
			tracing::error!("failed to send message: {e:?}");
		};
	});
}

return_val
}
```

Instead of returning a tuple of what passed and what failed, I had it return a vector of oneshot receivers. That way the result inside the tokio spawn thread will be exposed out.

**Comment by TorstenStueber** [comment]
@ebma We might want to implement different logic depending on the error message. I see three different kinds of errors: 1) transient errors, 2) problem that need to be fixed manually, 3) logical errors.

Case 1 could be a wrong sequence number. I don't know what exact logic we use now (channel accounts?), depending on that the best course of action is to request a new up to date sequence number or to retry with the same number.

Case 2 would be if the balance is too low. Do we have a notification mechanism? At least we should log the error and then the vault operator should watch that and act accordingly. In this case it does not make sense to retry immediately.

Case 3 should hopefully never happen – this would be a bug in the vault code. Nothing we can do here right now.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/340?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber
