### ISSUE TITLE
Fix 'auto-register' not working properly for Stellar assets with less than 4 characters

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#344]

**Comment by ebma** [comment]
We might not need any changes for this. To be seen with the outcomes of #346

**Comment by erasmus** [comment]
@ebma [#346](https://github.com/pendulum-chain/spacewalk/issues/346) is closed. Do we need this ticket?

**Comment by erasmus** [comment]
Awaiting final QA on a local machine from @b-yap

**Comment by ebma** [comment]
It should indeed work as is, without adding further changes. We can wait for @b-yap to confirm, but I'm quite confident about it.

**Comment by ebma** [comment]
We saw on Foucoco/Amplitude that this works as expected. Closing now
