### ISSUE TITLE
Increase time window for fetching SCP messages from overlay

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#354]
To increase the time window where our vault clients can fetch SCP messages from the overlay instead of from archive nodes, we will change the [MAX_SLOTS_TO_REMEMBER](https://github.com/stellar/stellar-core/blob/ca2fb06059c15442cb4c9a8c89de1a8fc3579a39/docs/stellar-core_example.cfg#L478) to **`14400`**.
By changing it to `14400` we increase the time window to 24 hours.

We need to update [this](https://github.com/pendulum-chain/spacewalk/blob/befd6fe8de903407e212902956398df25b50e8f3/clients/vault/src/oracle/constants.rs#L19) constant to that same value once done.

**Comment by TorstenStueber** [comment]
Of course this is only possible if we query only nodes whose `MAX_SLOTS_TO_REMEMBER` has this high value.

This depends of course on the configuration parameter defined for the pallet.
