### ISSUE TITLE
Improve info and usage of log messages

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#356]
We should make some effort to improve the info in some of our log messages.  Also, we should remove unnecessary log messages that clutter the output of our vault clients.

I'd recommend we:
- Remove the log messages about removing an old entry in `vault::oracle::types`
- Change the log level or reword the log messages in `stellar_relay_lib::connection::connector::message_handler`
- Add log messages that describe the current status of issue/redeem request execution. E.g. I noticed that the client does not log a statement once it tries to execute (and successfully executed) a new issue request

Think of it from the perspective of an external vault operator. When running the vault client you want to be able to choose between log levels that suit your needs. For example, you'd expect that:
- the 'info' level shows you log messages about the general operation of the vault client, ie. it informs you about current execution steps (receiving/finding a new issue/redeem event on-chain, executing that issue, etc). 
- the 'debug' level contains information that is useful for debugging the problem, but too detailed for general use
- the 'warn' level really only contains warnings, ie. messages that require actions from the operator or similar.

**Comment by vadaynujra** [comment]
@ebma is this required for the Pendulum main launch?

**Comment by ebma** [comment]
@vadaynujra it might be relevant for external vault operators. So I'd say yes.
