### ISSUE TITLE
Add NGN, EUR and AUD assets to Spacewalk

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/spacewalk#358]

**Comment by TorstenStueber** [comment]
@vadaynujra isn't this a task ticket instead? I assume that we only need to execute an extrinsic and don't need to change code (?)

**Comment by vadaynujra** [comment]
@TorstenStueber I'm not sure maybe @ebma is best to answer that. From my perspective, this will update the list of tokens that are enabled on Spacewalk, so a code change?

**Comment by ebma** [comment]
It should be a task ticket, no code changes required.

**Comment by TorstenStueber** [comment]
@vadaynujra can you move it to the tasks repo, please?

**Comment by vadaynujra** [comment]
New ticket created [here](https://github.com/pendulum-chain/tasks/issues/87). Please close / delete this one @TorstenStueber

**Comment by TorstenStueber** [comment]
Thanks, will do.
