### ISSUE TITLE
Support 'confirm' SCP messages in the stellar-relay when proving transaction validity

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#360]
# Problem
With the current implementation, the `stellar-relay` pallet only considers `ScpStatementExternalize` consensus messages to prove the validity of a Stellar transaction. However, we identified that Stellar archive entries usually only contain just **one** externalized message but many other 'ScpStatementConfim` or `ScpStatementPrepare` messages. This means that we currently cannot use archive entries to submit 'execute...' extrinsics, since this one externalized message is not enough.

# Solution
We want to change the validation logic used in the `stellar-relay` pallet to also consider `ScpStatementConfirm` messages. If we combine all 'confirm' and 'externalize' messages contained in archive entries, we should be build valid proofs even when missing the relevant consensus messages when they are emitted on Stellar's overlay network.

The reasoning why we can do this can be found on [this](https://www.notion.so/satoshipay/Archived-SCP-Messages-6801530d58d44f1fba1208db27ddee03#b052bb35b2fa416ea69034c5a2b34ae9) Notion page. For our implementation, we will follow the 'simplified approach' described [here](https://www.notion.so/satoshipay/Archived-SCP-Messages-6801530d58d44f1fba1208db27ddee03?pvs=4#b052bb35b2fa416ea69034c5a2b34ae9). 

### Steps
Note: The structure of `ScpStatements` can be found [here](https://stellar-sdk.readthedocs.io/en/stable/api.html#scpstatement). This is relevant for the next steps.  

Extend the logic of [this](https://github.com/pendulum-chain/spacewalk/blob/06873f16c4a7ab884e4759d98b7b86c712e0c0ae/pallets/stellar-relay/src/lib.rs#L577-L586) `match` statement:
- [ ] Add a new branch for `ScpStConfirm` pledges. Add logic that is very similar to the check for externalized messages, ie. check that the transaction set hash contained in the `ScpBallot` of the pledge matches the one we expect. **Note** that you might have to slightly adapt the `get_tx_set_hash` function because the names for the ballots differ between 'externalize' and 'confirm' messages (ie. it's either `commit` or `ballot`). 
- [ ] Ensure that all statements contained in the envelopes refer to the same `nH` value. 

By checking if the transaction set hash contained in the externalized/confirmed ballot matches the expected, we make sure that the consensus messages are related to the same value and the value we are looking for simultaneously.

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/360?planning-poker) with Zenhub @b-yap @TorstenStueber

**Comment by TorstenStueber** [comment]
I added [additional conditions](https://www.notion.so/satoshipay/Archived-SCP-Messages-6801530d58d44f1fba1208db27ddee03?pvs=4#66776f6d3f8241bc9be31937e09b2404) to the notion page that need to be tested in order to verify whether the messages are correct.

An example implementation of this complete checking procedure (in TypeScript instead of Rust) can be found [here](https://github.com/TorstenStueber/scp-messages/blob/main/src/checkConsensus.ts).

**Comment by ebma** [comment]
Thanks, @TorstenStueber. I'll try to implement the other conditions to the validation function as well. But in that approach, you mention that we should compare the contained quorum hash to the contained hash in the `ScpHistoryEntryV0`. We don't have access to that entry in our validation function, and we probably don't need to since we store all validators and their organizations on-chain and can verify if the message builds a valid quorum or not. Thus, I'll have to merge those extra conditions with our existing logic.

**Comment by TorstenStueber** [comment]
@ebma I find this acceptable. Eventually I would like that we don't need to hard code the quorum sets in the storage but extract them from the SCP messages themselves (that's how SCP is meant to work and that is how we can dynamically react to Tier 1 changes – one of the future proposals).

But for now let's go with the simpler implementation to reuse as much as we already have in the code.
