### ISSUE TITLE
Improve exported metrics for usage in Grafana dashboards

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#368]
To make it easier to label the respective metrics in Grafana dashboards, see [this](https://github.com/pendulum-chain/tasks/issues/40) ticket, we should add another field to the metrics emitted by the prometheus exporter of the Spacewalk client.

## TODO
We should add a field called `display_name` or similar to each exported metric. This `display_name` should be compact but expressive. It should mention the currency, but also combine the fields `status` or `type` into it, if available. 

### Examples
- The issue/redeem count gauges should say something like: 
```
issue_count{currency="XCM(0)_Stellar(USDC:GAK...)", status="completed", display_name="XCM(0)_USDC - completed"}
issue_count{currency="XCM(0)_Stellar(USDC:GAK...)", status="expired", display_name="XCM(0)_USDC - expired"}
issue_count{currency="XCM(0)_Stellar(USDC:GAK...)", status="open", display_name="XCM(0)_USDC - open"}
```
- The stellar balance gauges should say something like:
```
stellar_balance{currency="XCM(0)_Stellar(USDC:GAK...)", type="actual", display_name="XCM(0)_USDC - actual"}
stellar_balance{currency="XCM(0)_Stellar(USDC:GAK...)", type="actual", display_name="XCM(0)_USDC - required lowerbound"}
stellar_balance{currency="XCM(0)_Stellar(USDC:GAK...)", type="actual", display_name="XCM(0)_USDC - required upperbound"}
```

For context, this is how metrics are exported at the moment.
![image](https://github.com/pendulum-chain/spacewalk/assets/6690623/541b2835-e46b-4783-be67-f355147bba41)

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/368?planning-poker) with Zenhub @adelarja @b-yap

**Comment by TorstenStueber** [comment]
@ebma is this still relevant? If yes, please move to Ready.

Also note that this ticket here blocks https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/tasks/40

**Comment by ebma** [comment]
Yes, I think this is still relevant.
