### ISSUE TITLE
Change `CustomMetadata` for asset registry pallet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#375]
We should adjust the `CustomMetadata` struct to our needs. Since we don't really need any of the additional metadata that is defined at the moment, we can also leave it empty.

This is related to [this](https://github.com/pendulum-chain/pendulum/issues/275) ticket and required for [this](https://github.com/pendulum-chain/pendulum/pull/276) PR.

**Comment by ebma** [comment]
Other examples of `CustomMetadata`:
- [Centrifuge](https://github.com/centrifuge/centrifuge-chain/blob/222581d870cbbbdcedabbd36f5c352be6b94f252/libs/types/src/tokens.rs#L226-L243)
- [interbtc](https://github.com/interlay/interbtc/blob/9e53f12f39a97fd2e888a6df6721131c694c2bb3/primitives/src/lib.rs#L513-L517)
- [acala](https://github.com/AcalaNetwork/Acala/blob/94c2d893b50f804c56451cc00f3f2f566630d3e8/primitives/src/currency.rs#L642) / [bifrost](https://github.com/bifrost-finance/bifrost/blob/46348b9463c94e54d77893e945e6feb181f93271/pallets/asset-registry/src/lib.rs#L91) (but they use a custom implementation of an asset registry pallet)
- [mangata](https://github.com/mangata-finance/substrate/blob/5002c089a660699d21a3ed7b26a0a66778d32266/primitives/mangata-types/src/assets.rs#L19-L24)

interbtc and mangata both store a `fee_per_second` parameter in the metadata but I'm not yet sure how exactly this is used.

**Comment by TorstenStueber** [comment]
@ebma Looks like all these chains seem to use the `fee_per_second` only for the `AssetRegistryTrader`. Do we actually use that? I don't think so, we have a different Trader definition in our xcm-executor pallet.

**Comment by TorstenStueber** [comment]
It feels wrong to me to take over these complex definitions before we understand them properly. I would go with a minimal definition now (i.e., remove `fee_per_second`) and add it or other values back when we have more time to understand their effect and when we see a need for them.
