### ISSUE TITLE
Update Foucoco metadata

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#378]
We need to update the metadata for Foucoco, now that we restarted the chain with a new genesis.

**Comment by ebma** [comment]
@pendulum-chain/product This change is necessary because, at the moment, our Foucoco Spacewalk vault is not able to connect to the new Foucoco chain because we changed some internal metadata parameters. 
Afterward, we need to redeploy the nodes as described in [this](https://github.com/pendulum-chain/tasks/issues/106) follow-up ticket.

**Comment by vadaynujra** [comment]
@ebma since this also relates to the Foucoco work, should we add a label to reflect this was 'surprise' work?
