### ISSUE TITLE
Investigate origin and severity of `ExternalizedNHMismatch` error

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#382]
Some parts of our integration tests started failing quite frequently with the following error:
```
thread 'test_execute_open_requests_succeeds' panicked at 'Failed to execute issue: SubxtRuntimeError(Runtime(Module(ModuleError { pallet: "StellarRelay", error: "ExternalizedNHMismatch", description: [], error_data: ModuleErrorData { pallet_index: 10, error: [7, 0, 0, 0] } })))', clients/vault/tests/vault_integration_tests.rs:134:10
```
see eg, [this](https://github.com/pendulum-chain/spacewalk/actions/runs/5645495683/job/15291381813) and [this](https://github.com/pendulum-chain/spacewalk/actions/runs/5641646617/job/15280032414?pr=377) CI job.
Since it's not always the same test function that fails, we can assume that this error only happens occasionally.

However, we should try to identify how likely this error occurs and why. It might be that the underlying problem is quite severe and we should make sure that the vault is able to successfully provide proof for an issue/redeem request to the stellar-relay pallet _all the time_, now that we fixed the archive problem.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/382?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by ebma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/382?planning-poker) with Zenhub @b-yap

**Comment by TorstenStueber** [comment]
Any clue what `ExternalizedNHMismatch` means? Has it something to do with externalize messages?

**Comment by TorstenStueber** [comment]
Oh, that is unexpected. I would like to see such an example where this assumption does not hold (for whoever picks up this ticket).

**Comment by ebma** [comment]
@pendulum-chain/product investigating this problem is very important and should have a very high priority in the backlog.

**Comment by prayagd** [comment]
@ebma Sure, moved it to the ready column on the top
