### ISSUE TITLE
Investigate and fix occasional consensus error

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#386]
Sometimes, Spacewalk's integration tests fail with the following error. 
```
thread 'test_cancel_scheduler_succeeds' panicked at 'failed to create block: Rpc(ClientError(Call(Custom(ErrorObject { code: ServerError(14000), message: "Consensus Error: Import failed: Potential long-range attack: block not in finalized chain.", data: None }))))', /home/runner/work/spacewalk/spacewalk/clients/runtime/src/rpc.rs:164:14
```
The error might be related to the manual consensus seal mechanism that we use in our integration tests, at least the first time I encountered this error was after adding manual consensus. This error only occurs occasionally though, so it's a little difficult to pin down.

Some examples of failing CI jobs with that error:
- https://github.com/pendulum-chain/spacewalk/actions/runs/5864353088/job/15903219626#step:10:2840
- https://github.com/pendulum-chain/spacewalk/actions/runs/5864353088/job/15905305417?pr=384#step:10:2851
- https://github.com/pendulum-chain/spacewalk/actions/runs/5864463229/job/15911382875?pr=343#step:10:2899

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/386?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber
