### ISSUE TITLE
Create client/runner that supports auto-updating the vault client

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#398]
The vault client on spacewalk would have to manually update the new releases that we would be rolling out. In order to avoid this and save vault client effort, we want to implement an auto-updater mechanism that automatically updates the vault client for new releases.

## TODO
We will try to adopt [this](https://github.com/interlay/interbtc-clients/tree/master/runner) implementation. 
Since we don't have a client runner for the 'oracle' or 'faucet, the runner will only have to support the [ClientType](https://github.com/interlay/interbtc-clients/blob/06fd50bff33c0580aa47487496eb5c5488908a52/runner/src/runner.rs#L34) `vault` for now. 

This ticket is related to https://github.com/pendulum-chain/tasks/issues/46.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/398?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
