### ISSUE TITLE
Add pooled reward pallet

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#403]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

Add the current reward pallet from Interlay to Spacewalk: https://github.com/interlay/interbtc/tree/1b90616692dcce55749616b4c60bdab228279909/crates/reward

This pallet is different from the old reward pallet in Spacewalk because it supports pools, a feature we need for the rewards system.

## Technical considerations
* the hostchain will set the PoolId configuration of the pallet to CurrencyId
* the hostchain will set the StakeId configuration of the pallet to AccountId

**Comment by ebma** [comment]
@TorstenStueber is this a duplicate of #404 or did you want this ticket to add other changes?

**Comment by TorstenStueber** [comment]
I am confused about this myself. Must be a duplicate. Closed.
