### ISSUE TITLE
Add pooled reward pallet

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#404]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

Add the current reward pallet from Interlay to Spacewalk: https://github.com/interlay/interbtc/tree/1b90616692dcce55749616b4c60bdab228279909/crates/reward

This pallet is different from the old reward pallet in Spacewalk because it supports pools, a feature we need for the rewards system.

We should call this pallet `PooledRewards`.

## Additional tasks
* Identify all places in Spacewalk that reserve or unreserve collateral of vaults of nominators.
   * Every time collateral is reserved, call `deposit_stake` of `PooledRewards`, where `pool_id` is the currency id of the collateral, `stake_id` is the account id of the vault itself or the nominator account, `amount` is the increment of reserved collateral
   * Every time collateral is unreserved, call `withdraw_stake` accordingly

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/404?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
