### ISSUE TITLE
Create new reward-distribution pallet

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#405]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

Create a new pallet from scratch that takes care of the collateral reward logic.

## Additional tasks
* Add a configuration parameter `Currency` of type `Currency<Self::AccountId>` (which is a reference to pallet-balances)
* Add a storage variable `RewardPerBlock` (of type `Balance`, using `OptionQuery`) that maintains the number of reward tokens minted per block – it is 0 by default
* Add a storage variable `RewardsAdaptedAt` (of type `BlockNumber`, using `OptionQuery`) that stores the active block number of the last time `RewardPerBlock` has been adapted
* Add a reference to the security pallet so that the reward-distribution pallet can use `active_block_number` and `parachain_block_expired` functions
* Add constant pallet configuration parameters `DecayInterval` (of type `BlockNumber`) and `DecayRate` (of type `Perquintill`).
* Add a root extrinsic that allows to set `RewardPerBlock`. It will also set `RewardsAdaptedAt` to the current active block number.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/405?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
