### ISSUE TITLE
Maintain a list of currency ids used as collateral

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#408]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

This ticket depends on https://github.com/pendulum-chain/spacewalk/issues/405

In the `rewards-distribution` pallet maintain a list of currency ids used as collateral (this can be a configuration parameter of the new `reward-distribution` pallet or a storage value (a vector of `CurrencyId`) that adds new elements automatically whenever a new pool id – that has not been seen so far – is used in the `PooledRewards` pallet).

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/408?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
I believe we can close this issue since this functionality is addressed in [this](https://github.com/pendulum-chain/spacewalk/pull/415) PR.

**Comment by ebma** [comment]
Not needed anymore because similar functionality was implemented in https://github.com/pendulum-chain/spacewalk/pull/415.
