### ISSUE TITLE
Create a Github workflow to automatically build Spacewalk binaries

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#410]
We need to improve our current release management process. It should work as follows:

Pushing a new tag to the `main` branch triggers a GitHub workflow action that calls into a Gitlab API that triggers the compilation pipeline for all binaries (vault + runner).

On Gitlab, the pipeline:
1. Builds artifacts of the **vault client** for each network (Pendulum, Amplitude, Foucoco) and one artifact for the **runner** client. 
1. It also generates the sha256 checksums for each vault client and puts that into an extra file ‘sha256sums.txt’. These are used later when calling the `setPendingClientRelease` extrinsic of the `clients-info` crate.
1. Creates a new draft release on the Spacewalk repository on Github and uploads these binaries to that draft release. 
The tag should resemble the version number and should be used as the name of the release.

The immediate outcome of this ticket is the workflow file for triggering the pipeline on Gitlab. The other changes mentioned in this ticket have to happen on Gitlab of course.

### Notes
For reference, Interlay has [this](https://github.com/interlay/interbtc-clients/blob/11d6d99c9ce74ab36dfbe7b8efe6f5382f9fe3bc/.github/workflows/cargo-test.yml) workflow to do all this on Github.

**Comment by ebma** [comment]
@pendulum-chain/product this ticket is related to our improved release management described in [this](https://www.notion.so/satoshipay/Spacewalk-release-management-b20411b93c864ba1a30bfab5d625ce8b?pvs=4) document.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/410?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber
