### ISSUE TITLE
Allow calling extrinsics of `clients-info` crate from authorized accounts

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#411]
We should change the `clients-info` crate to allow calling the `set...ClientRelease` extrinsics from root or an authorized account. This way, we don't have to create an extra referendum each time we want to update our Spacewalk clients but can rely on using a multi-sig account instead. 

### Notes
For implementing the logic for the authorized accounts, you can draw inspiration from the [implementation](https://github.com/pendulum-chain/oracle-pallet/blob/master/pallets/dia-oracle/src/lib.rs) of the DIA oracle pallet.

**Comment by ebma** [comment]
@pendulum-chain/product [this](https://www.notion.so/satoshipay/Spacewalk-release-management-b20411b93c864ba1a30bfab5d625ce8b?pvs=4) ticket is related to our improved release management described in this document. It has high priority.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/411?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by vadaynujra** [comment]
@ebma considering this as a blocker for the public launch on Amplitude. Let me know if that's not the case?

**Comment by ebma** [comment]
Yes, I agree and would also consider this required for public launch.
