### ISSUE TITLE
4FC-05 Commented out code

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#417]
We need to clean up some commented-out code and TODO comments that were introduced by #385.

**Comment by ebma** [comment]
@pendulum-chain/product this is a follow-up to the changes for #257 and we should work on this very soon. We only split this out of the original ticket to progress faster with fixing the Spacewalk issues on testnet.

**Comment by annatekl** [comment]
@ebma @b-yap is this relevant to pick it up for the current spacewalk launch?

**Comment by ebma** [comment]
No @annatekl. But wouldn't hurt to work on this soon.

**Comment by TorstenStueber** [comment]
@prayagd @annatekl Any reason this is not in Ready yet?

**Comment by b-yap** [comment]
This ticket also requires cleaning up "todos" and commented codes. 
But here are the following _`todos`_ carried over from **_Interlay_**:

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/clients/runtime/src/rpc.rs#L605 [Interlay code here](https://github.com/interlay/interbtc-clients/blob/2402914c1a0f51803cf641a8446f420243e62e56/runtime/src/rpc.rs#L1638)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/vault-registry/src/tests.rs#L565 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/vault-registry/src/tests.rs#L464)

*  https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/vault-registry/src/lib.rs#L1085 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/vault-registry/src/lib.rs#L959)

*  https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/vault-registry/src/types.rs#L627 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/vault-registry/src/types.rs#L625)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/issue/src/lib.rs#L557 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/issue/src/lib.rs#L491)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/issue/src/lib.rs#L710 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/issue/src/lib.rs#L636) 

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/redeem/src/lib.rs#L593-L594 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/redeem/src/lib.rs#L478)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/staking/src/lib.rs#L196 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/staking/src/lib.rs#L193)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/staking/src/lib.rs#L619 [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/staking/src/lib.rs#L594)

* https://github.com/pendulum-chain/spacewalk/blob/56b9601d7503b54122578b47ad939f1b20024175/pallets/reward/src/lib.rs#L245-L249  [Interlay code here](https://github.com/interlay/interbtc/blob/dec38ebf924d94158c4eeac9a2f795d09cc39f60/crates/reward/src/lib.rs#L287-L290)

We can keep them as is, or cherry pick any that we think we can do ourselves

**Comment by ebma** [comment]
Thanks for the nice overview @b-yap 🙏  The code samples of interlay's code you linked to are all still occurring on their latest `main` branch? If so, I think it's fine if we don't fix them for now.

**Comment by b-yap** [comment]
@ebma question:

https://github.com/pendulum-chain/spacewalk/issues/257#issuecomment-1706309694
>  one of the concerns of  _4FC-05 Commented out code_ are
https://github.com/pendulum-chain/spacewalk/blob/ad68c16f55141357d14df66d40717b42d089c96c/clients/vault/src/system.rs#L718-L720
and
https://github.com/pendulum-chain/spacewalk/blob/ad68c16f55141357d14df66d40717b42d089c96c/clients/vault/src/system.rs#L660
Do you know what to do here, or is a separate ticket needed to address this?

You redirected to this ticket -> [Add faucet to send test tokens to accounts #161](https://github.com/pendulum-chain/spacewalk/issues/161)

If I understand correctly, the [deployed faucet](https://pendulum.gitbook.io/pendulum-docs/community/testnet-faucet) is only for testnet:

```rust
if let Some(faucet_url) = &self.config.faucet_url {
      let is_public_network =
        self.spacewalk_parachain.is_public_network().await.unwrap_or_else(|error| {
          // Sometimes the fetch fails with 'StorageItemNotFound' error.
          // We assume public network by default
          tracing::warn!(
          "Failed to fetch public network status from parachain: {error}. Assuming public network."
        );
          true
        });

      if !is_public_network {
        // use account id of the spacewalk parachain
        let account_id = self.spacewalk_parachain.get_account_id().pretty_print();
        let url = format!("{faucet_url}?to={account_id}");
        let response = reqwest::get(url.clone()).await;
      }

    }
```
Is it correct to use the parachain's account_id? 

The log:
```
Feb 13 22:54:25.198  INFO vault::system: THE FULL URL: https://faucet-service.pendulumchain.tech/fund?to=6izw2Zx6zcgA44G51ptCKWbsLeyDE4hgVcvKifAkfDr2tATc
Feb 13 22:54:27.928  INFO vault::system: THE RESPONSE: Ok(Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("faucet-service.pendulumchain.tech")), port: None, path: "/fund", query: Some("to=6izw2Zx6zcgA44G51ptCKWbsLeyDE4hgVcvKifAkfDr2tATc"), fragment: None }, status: 500, headers: {"date": "Tue, 13 Feb 2024 14:54:27 GMT", "content-type": "text/html; charset=utf-8", "content-length": "36", "connection": "keep-alive", "ratelimit-policy": "60;w=60", "ratelimit-limit": "60", "ratelimit-remaining": "59", "ratelimit-reset": "60", "content-security-policy": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", "cross-origin-opener-policy": "same-origin", "cross-origin-resource-policy": "same-origin", "origin-agent-cluster": "?1", "referrer-policy": "no-referrer", "strict-transport-security": "max-age=15724800; includeSubDomains", "x-content-type-options": "nosniff", "x-dns-prefetch-control": "off", "x-download-options": "noopen", "x-frame-options": "SAMEORIGIN", "x-permitted-cross-domain-policies": "none", "x-xss-protection": "0", "access-control-allow-origin": "*", "etag": "W/\"24-EgLvasLBtN4AHHuzd2PfDR6mVDg\""} })
```

When I ran the url on browser, it shows 
`Server Error. Please try again later`.

**Comment by b-yap** [comment]
thanks for the heads up, @gianfra-t !

**Comment by b-yap** [comment]
I started to work on https://github.com/pendulum-chain/spacewalk/blob/35a4895dffac22c487a89e6f1115350dbda777fd/pallets/replace/src/benchmarking.rs#L154

And found out that Interlay made a few changes: [chore: replace benchmarks #1025](https://github.com/interlay/interbtc/pull/1025/files#diff-f2a33d3b36bada9b5be005d9e6ec6e35e01776db4290c98877b7de58cc508964L182)

I was following the changes but found some differences that made it too much, should I truly use thiers. 
Example: 

* Interlay use [orml_tokens](https://github.com/interlay/interbtc/blob/cb112ed21435f007a17ccb8e4493a01d0c0ae400/crates/currency/src/lib.rs#L88) to deposit amounts, while we use [orml_currencies](https://github.com/pendulum-chain/spacewalk/blob/35a4895dffac22c487a89e6f1115350dbda777fd/pallets/currency/src/lib.rs#L62).
* Interlay has additional storages like [Aggregate](https://github.com/interlay/interbtc/blob/cb112ed21435f007a17ccb8e4493a01d0c0ae400/crates/oracle/src/lib.rs#L121-L123) that spacewalk doesn't have.
* Interlay's setup has [BTC related code](https://github.com/interlay/interbtc/blob/cb112ed21435f007a17ccb8e4493a01d0c0ae400/crates/replace/src/benchmarking.rs#L189-L198) that we don't need.

Instead, I will only verify the changes directly:
```rust
withdraw_replace {
		...
		register_vault::<T>(vault_id.clone());
		...
		let vault : DefaultVault::<T> = VaultRegistry::<T>::get_vault_from_id(&vault_id).expect("should return a vault");
		let to_be_replaced_tokens = vault.to_be_replaced_tokens;
	}: _(RawOrigin::Signed(vault_id.account_id.clone()), vault_id.currencies.clone(), amount.amount())
	verify {
		let vault : DefaultVault::<T> = VaultRegistry::<T>::get_vault_from_id(&vault_id).expect("should return a vault");
		let updated_to_be_replaced_tokens = vault.to_be_replaced_tokens;

		assert!(to_be_replaced_tokens > updated_to_be_replaced_tokens);
	}
```


But currently have to deal with:
```
2024-02-14 20:49:23 panicked at 'Expected Ok(_). Got Err(
    Module(
        ModuleError {
            index: 19,
            error: [
                0,
                0,
                0,
                0,
            ],
            message: Some(
                "ParachainNotRunning",
            ),
        },
    ),
)', /Users/b.carlayap/projects/spacewalk/pallets/redeem/src/benchmarking.rs:156:9    
Error: Input("Error executing and verifying runtime benchmark: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x3532d - <unknown>!rust_begin_unwind\n    1: 0x980a - <unknown>!core::panicking::panic_fmt::h77cb6fbeac3ac4ae\n    2: 0xbdf48 - <unknown>!<redeem::benchmarking::SelectedBenchmark as frame_benchmarking::utils::BenchmarkingSetup<T>>::instance::h674cb72c20b90907\n    3: 0x156fb1 - <unknown>!redeem::benchmarking::<impl frame_benchmarking::utils::Benchmarking for redeem::pallet::Pallet<T>>::run_benchmark::h74c840d51638c276\n    4: 0x12f2f6 - <unknown>!<spacewalk_runtime_standalone::Runtime as frame_benchmarking::utils::runtime_decl_for_benchmark::BenchmarkV1<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,spacewalk_runtime_standalone::RuntimeCall,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<spacewalk_runtime_standalone::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<spacewalk_runtime_standalone::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<spacewalk_runtime_standalone::Runtime>,frame_system::extensions::check_mortality::CheckMortality<spacewalk_runtime_standalone::Runtime>,frame_system::extensions::check_nonce::CheckNonce<spacewalk_runtime_standalone::Runtime>,frame_system::extensions::check_weight::CheckWeight<spacewalk_runtime_standalone::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<spacewalk_runtime_standalone::Runtime>)>>>>::dispatch_benchmark::h6066f53bffd4da82\n    5: 0x1177ec - <unknown>!Benchmark_dispatch_benchmark")
```

after running:
```
./target/release/spacewalk-standalone benchmark pallet \
    --chain dev \
    --execution=wasm \
    --wasm-execution=compiled \
    --pallet "*" \
    --extrinsic "*" \
    --steps 50 \
    --repeat 20 \
    --output pallets/all-weight.rs
```

**Comment by ebma** [comment]
The 'ParachainNotRunning' error indicates that the oracle pallet does not have all the prices available that it needs. The 'need' is defined by the currencies added to the 'oracle_keys' of the oracle pallet which you can check in the chain_spec. Did we change something about it? I don't think so 🤔

**Comment by b-yap** [comment]
@ebma 
Not sure what the actual fix is; I[ rearranged the code](https://github.com/pendulum-chain/spacewalk/commit/efc306c8de377468c6f0e633b44f30f96d4a55c6) of both benchmarks of `Replace` and `Redeem` pallets, following the benchmark of the `Issue` pallet since it worked fine.

**Comment by ebma** [comment]
Hmm okay weird, not sure what it fixed it in your comment.
