### ISSUE TITLE
Integration tests for new vault rewards implementation 

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/spacewalk#423]
Following the completion of tasks in [this pendulum issue](https://github.com/pendulum-chain/tasks/issues/47), it would be nice to add some integration tests that ensure that the rewards are being distributed according to the model.

We need to test these main things:
- That the rewards per block are properly distributed based on total collateral staked in usd.
- That the fees are also properly distributed based on collateral staked in usd.
- That the nominators/vault operators get the corresponding value based on their vault's stakes and can properly withdraw.

For this, we need to ensure in the set-up of the tests that:
- There exists multiple vaults, with multiple collateral and wrapped currencies.
- That this vaults are both backed in collateral by their operators and nominators.

Following the setup, we must ensure that this vaults issue some amount of tokens to test the fee distribution, and that some blocks move forward to test the per block distribution. This two tests can be independent.

Finally, we must ensure that the rewards distributed follows the model:
 reward `vault_i` = ( stake_usd(`collateral_i`)/Total_stake_usd ) * `reward`.

Where `stake_usd()` is the total sum in usd of collateral across vaults_id that share that collateral and `Total_stake_usd` is the sum of `stake_usd` across all collateral currencies in the system.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/423?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber
