### ISSUE TITLE
Fix proof-building issue from archives on mainnet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#427]
We are currently facing some issues with proof-building on our Amplitude spacewak clients. 
The problem is that when fetching envelopes from the transaction archive, the archived entries contain 14 envelopes. 
Our calculation of [get_min_externalized_messages](https://github.com/pendulum-chain/spacewalk/blob/8bb0d639c6f2e23126f72e39f56c6a497cf2e2d4/clients/vault/src/oracle/types/constants.rs#L27) makes us require at least 15 envelopes for building a proof though, called [here](https://github.com/pendulum-chain/spacewalk/blob/8bb0d639c6f2e23126f72e39f56c6a497cf2e2d4/clients/vault/src/oracle/collector/proof_builder.rs#L135).
We should probably loosen this requirement a bit but not too much. I'm not yet sure what the exact science for this would be. Maybe we don't calculate it but use fixed values for mainnet and testnet respectively.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/427?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by b-yap** [comment]
@ebma 
Wondering if it's possible to remove the data from map (this new one, the `envelopes_map` and `txset_map`), once the proof is built?

**Comment by ebma** [comment]
Oh right, that's a good point I did not consider.. Maybe too risky to remove it right away? How about we use our `LimitedFifoMap` for this as well and define a limit? This way, the slots get removed automatically when it grows too large.

**Comment by prayagd** [comment]
@b-yap i assigned you and moved this to development, Hope that's ok?
