### ISSUE TITLE
move issuance logic to appropriate extrinsics in issue pallet

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/spacewalk#43]
In our spacewalk pallet, we have a reportStellarTransaction extrinsic.

The logic in the `reportStellarTransaction` extrinsic from the spacewalk pallet needs to be moved into the appropriate extrinsics in the `issue` pallet. The appropriate place to put this functionality is `execute_issue`.

The issue pallet has the following extrinsics: `request_issue`, `execute_issue`, `cancel_issue`, `set_issue_period`

**Comment by ebma** [comment]
Superseded by #90.
