### ISSUE TITLE
Add environment variable options to Spacewalk

### ISSUE THREAD

**Issue by zoveress** [pendulum-chain/spacewalk#431]
Can we add the parameters that spacewalk uses as environment variables as well? So the way it would work that spacewalk would take the environment variables instead of the command line parameters if there is nothing defined in the command line.

**Comment by ebma** [comment]
@pendulum-chain/product this change makes running a vault client easier and more secure in cloud infrastructure.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/431?planning-poker) with Zenhub @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
Apparently there is an `env` flag in `clap` so we can just add another macro to the config parameters, like [here](https://github.com/interlay/interbtc-clients/blob/93a3330a11f267054aebeca689e224afae147a93/bitcoin/src/cli.rs#L23).

**Comment by TorstenStueber** [comment]
@ebma @prayagd can we move this to Ready or Icebox?

**Comment by ebma** [comment]
Since I expect this to be a quick one, I'd say we move it to 'ready' and not 'icebox'

**Comment by TorstenStueber** [comment]
@ebma alright. I moved it to the bottom of Ready. Feel free to move up and give higher priority.

**Comment by TorstenStueber** [comment]
@annatekl why has this been moved to Icebox in contradiction to the messages above?

**Comment by annatekl** [comment]
misread, moved back to ready

**Comment by annatekl** [comment]
@ebma does this require runtime upgrade or root transaction?

**Comment by ebma** [comment]
No it does not.
