### ISSUE TITLE
Add configuration for automatic changelog generation

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#434]
In order to facilitate the creation of new releases, we should use a tool to automatically generate changelogs based on the commit history. 
We should use the [git-chglog](https://github.com/git-chglog/git-chglog) tool because it nicely integrates into GitHub actions, see for example [this](https://github.com/interlay/interbtc-clients/blob/11d6d99c9ce74ab36dfbe7b8efe6f5382f9fe3bc/.github/workflows/cargo-test.yml) workflow.

This is related to #410.

**Comment by annatekl** [comment]
@ebma is this required for the next released that comes in with rewards and vault fixes?

**Comment by ebma** [comment]
@annatekl no it's not required. It's a nice-to-have feature but I haven't found the time yet to work on it yet. It just removes a little overhead when creating the changelogs but we can do that manually for now, no problem.
