### ISSUE TITLE
Vault client retries transaction submission for unrecoverable errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#452]
At the moment, the vault client will permanently retry the submission of a transaction, even if it received some error that makes clear that a resubmission will not succeed anyways.

For example looking at the following logs, when receiving the `InvalidQuorumSetNotEnoughValidators` it's clear that a resubmission of the same extrinsic will result in the same error. Thus, we should not retry because the vault needs to pay the transaction gas fee for each extrinsic call, also the failing ones.

```
Nov 23 18:50:55.065  INFO vault::oracle::agent: get_proof(): Successfully build proof for slot 49136081
Nov 23 18:52:10.528  WARN runtime::retry: Subxt runtime error: Runtime error: Module(ModuleError { pallet: "StellarRelay", error: "InvalidQuorumSetNotEnoughValidators", description: [], error_data: ModuleErrorData { pallet_index: 68, error: [12, 0, 0, 0] } }) - next retry in 0.860 s    
Nov 23 18:52:10.528  WARN runtime::retry: Subxt runtime error: Runtime error: Module(ModuleError { pallet: "StellarRelay", error: "InvalidQuorumSetNotEnoughValidators", description: [], error_data: ModuleErrorData { pallet_index: 68, error: [12, 0, 0, 0] } }) - next retry in 1.240 s    
Nov 23 18:52:10.543  WARN runtime::retry: Subxt runtime error: Runtime error: Module(ModuleError { pallet: "StellarRelay", error: "InvalidQuorumSetNotEnoughValidators", description: [], error_data: ModuleErrorData { pallet_index: 68, error: [12, 0, 0, 0] } }) - next retry in 1.053 s    
Nov 23 18:52:10.776  WARN runtime::retry: Subxt runtime error: Runtime error: Module(ModuleError { pallet: "StellarRelay", error: "InvalidQuorumSetNotEnoughValidators", description: [], error_data: ModuleErrorData { pallet_index: 68, error: [12, 0, 0, 0] } }) - next retry in 1.214 s    
Nov 23 18:52:15.169 ERROR vault::issue: Issue task for slot 49136081 failed with error: "SubxtRuntimeError(Runtime(Module(ModuleError { pallet: \"StellarRelay\", error: \"InvalidQuorumSetNotEnoughValidators\", description: [], error_data: ModuleErrorData { pallet_index: 68, error: [12, 0, 0, 0] } })))"
```

## TODO
We should adjust the [retry logic](https://github.com/pendulum-chain/spacewalk/blob/8bb0d639c6f2e23126f72e39f56c6a497cf2e2d4/clients/runtime/src/rpc.rs#L236) and not retry the submission for unrecoverable errors returned by the Stellar relay pallet.

**Comment by TorstenStueber** [comment]
@ebma Is it clear what exactly are unrecoverable errors? Or would you start with the error you indicate here?

**Comment by ebma** [comment]
I would take the assumption that any module error, ie. any error thrown by a pallet is unrecoverable. As far as I can tell, no Error thrown during the execution of either issue or redeem request can be solved by a mere resubmission of the same transaction.

**Comment by ebma** [comment]
I think we have to be a little more careful than that. Because for example, the vault's on-chain account having too few native tokens to pay for the transaction gas fee will result in an 'invalid transaction'-error. And this should indeed be retried until the vault's account is topped up again. Thus, we should add an extra case where we test if the error is a module/pallet error and not retry in those cases.

**Comment by gianfra-t** [comment]
I see, but isn't that similar to something like `ExceedLimitVolumeForRedeemRequest` from the redeem pallet? In the sense that a change in the state may in the future make the transaction valid, but requires input not just resumbition. In that case what would be the logic to define errors that are recoverable vs unrecoverable?

**Comment by ebma** [comment]
No, because the `ExceedLimitVolumeForRedeemRequest` can only be thrown when registering a new redeem request. Which is something that the user does. For the _execution_ of issue/redeem requests, I think there is no recoverable error.

**Comment by gianfra-t** [comment]
I understand. So if it is an action that the vault operator needs to do in order to rectify the tx (like you pointed out, gas fees), then it is recoverable. I will try to find more of this cases and modify the code.
