### ISSUE TITLE
Loosen requirement for quorum check in Stellar relay pallet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#457]
## Context
The check for valid quorum sets in the Stellar relay pallet is too strict in many cases and does not work well with archived messages. For more context, see [this](https://www.notion.so/23-11-29-Stellar-relay-consensus-issues-d587d75c4616429eb8c4a134dd54ece2) Notion page. 

## TODO
Change the logic so that it doesn't require _each_ organization to have >1/2 validators but it is still a valid quorum if the SCP messages are targeting >2/3 of organizations with at least >1/2 validators.

**Comment by annatekl** [comment]
@ebma can we get this ticket estimated?
