### ISSUE TITLE
Clean up Stellar secret keys

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#471]
We currently have some secrets for Stellar accounts lingering around in this repository. These are required for the successful execution of many integration tests. However it's not ideal to have these secrets available in this public repository and we need to clean this up. 

## TODO
- Create a config that holds the required Stellar account secrets required by all tests. We need at least 4 different account secrets for both public and test network in total because we need to have a source account and a destination account on each network. These are used when testing transfers. 
- Pass the necessary account secrets as environment variables instead. It's very easy to add a configuration that is populated with env variables using `clap`, see [here](https://github.com/interlay/interbtc-clients/blob/93a3330a11f267054aebeca689e224afae147a93/bitcoin/src/cli.rs#L23). 
- Replace all occurrences of hard-coded Stellar secret keys with keys passed to the config.
- Change the settings for the CI environment variables of this repository so that the keys are available for the tests. They also need to be provided in the Gitlab CI that is run for new releases, so reach out to @zoveress when working on this.

As part of this change, we should create new Stellar accounts and move the respective funds to those accounts. This way, we are sure that our testing accounts were never exposed publicly. This will also require changes to the script for topping up the testnet account [here](https://github.com/pendulum-chain/stellar-testnet-restoration).

**Comment by ebma** [comment]
@pendulum-chain/product this doesn't add a new feature but removes technical debt and improves the security of our Stellar keys by not publishing them publicly. I'd give it a higher priority.

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/471?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
@ebma do you agree? I would think that this does not interfere with the public launch.

Since these are all testnet secrets (?), I think it is merely more of annoyance if someone would steel them as we would have to recreate new accounts.

**Comment by ebma** [comment]
We don't have to fix this issue before the public launch. The secret keys that are exposed here are used on neither Foucoco, Amplitude nor Pendulum so there is no risk for Spacewalk on our production networks.

**Comment by prayagd** [comment]
Moving this to icebox as it is low priority

**Comment by ebma** [comment]
Can I veto moving this to the icebox? In theory, I agree it's a good candidate for the icebox because it's not relevant to the security of the bridge itself. But it's kind of important for our internal security because we might forget about those keys being exposed and we'd end up wondering what's going on when people start messing with the accounts. So IMO it would still be nice to fix it soon.

**Comment by ebma** [comment]
@zoveress we are now very close to merging the respective changes for this. Going forward, the CI running the Spacewalk tests needs to have access to some Stellar account secrets. We already configured the credentials on Github but not yet on Gitlab. You can find the required secrets in the 'Spacewalk Testing Stellar accounts' item. You will need to supply them somehow to the pipeline running the `cargo test` command. The environment variable names are [here](https://github.com/pendulum-chain/spacewalk/blob/df3fccc47676b5f947ecb7727b7624caed82ed22/.github/workflows/ci-main.yml#L58-L61).

**Comment by zoveress** [comment]
@ebma can you please specify the entire command or I just have to define the envars and thats it?

**Comment by ebma** [comment]
Yes, they just have to be available in the environment. Alternatively, you can pass them directly when running the `cargo test` command, ie.  SOURCE_STELLAR_SECRET_MAINNET=... SOURCE_STELLAR_SECRET_TESTNET=... DEST_xxx= cargo test --all --all-features`
Last but not least you could also put them into a `.env` file in the `clients` directory, similar to [this](https://github.com/pendulum-chain/spacewalk/blob/df3fccc47676b5f947ecb7727b7624caed82ed22/clients/.env.example). The tests would pick that up automatically
