### ISSUE TITLE
Add Stellar testnet archive URLs to vault client config

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#482]
Apparently, the Stellar testnet validators do have their own archives. They can be found here:
- `history.stellar.org/prd/core-testnet/core_testnet_001`
- `history.stellar.org/prd/core-testnet/core_testnet_002`
- `history.stellar.org/prd/core-testnet/core_testnet_003`

## TODO 
- In the code, we so far assumed that there are no archives for Stellar testnet. We should change this assumption and remove any code that prevents restoring proof messages from archives on Stellar testnet.
- We should also change our files for the Stellar overlay configuration on testnet to include these archive URLs.

**Comment by prayagd** [comment]
@ebma is this required for the upcoming pendulum launch?

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/482?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
No, it's not required.

**Comment by prayagd** [comment]
Should i move this to icebox then?

**Comment by ebma** [comment]
This is not required for the upcoming launch but it helps us test the vaults on Foucoco in a setting that is closer to the Amplitude/Pendulum networks because so far we couldn't test the use of Stellar archives on Foucoco. That's why I wouldn't move it to the icebox and instead give it a medium priority.
