### ISSUE TITLE
Change price conversion function in oracle pallet to work for assets with different decimals

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#489]
## Context
In Spacewalk we generally assume all assets to have the same amount of decimals. This assumption doesn’t hold though as the DOT token has 10 decimals while our other assets (used in Spacewalk) have 12 decimals. The conversion between the value of wrapped and collateral assets is among other things important for gauging the collateralization rates.

See [this](https://www.notion.so/satoshipay/Spacewalk-price-conversion-accuracy-c3ebac43432c403fbdace469f400e59f) Notion page. 

## TODO
- Change the price conversion so that it takes the decimals of assets into account

**Comment by ebma** [comment]
@pendulum-chain/product this is the ticket for solving the decimal issue.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/489?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
