### ISSUE TITLE
Improve robustness of Spacewalk vault integration tests

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#494]
The integration tests using Stellar mainnet are failing too often, probably when the network is very busy. We need to improve this because our CI needs to pass reliably. 

## TODO
- Check what's causing the mainnet integration tests to fail and try to prevent it. The logic of the tests overall should be fine as it's not always the same test failing.
- To do this, run `cargo test --package vault --features standalone-metadata --features integration-test --test vault_integration_tests ""`

**Comment by prayagd** [comment]
@annatekl can you please add epic and sprint to this?

**Comment by annatekl** [comment]
done @prayagd
