### ISSUE TITLE
Investigate occasional high CPU usage of vault clients

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#512]
It seems like sometimes, the vault clients' CPU usage increases up to 100% without any apparent reason. This leads to the vault client becoming unresponsive and not handling bridge requests anymore.

What we know:
- This issue happens across **all** Amplitude _and_ Pendulum vaults at around the same time.
- In the monitoring, we can see that the CPU usage increases from 50% to 100% within 45 minutes.
- Memory and disk usage are not increasing during this time window.
- After the periodic restart, the CPU usage goes back to ~50%
- There are no messages appearing in the logs (at least on 'INFO' log level).
- The Spacewalk-related metrics are unavailable for this timeframe which indicates that the whole client becomes unresponsive

<img width="1866" alt="image" src="https://github.com/pendulum-chain/spacewalk/assets/6690623/6abab511-733b-4d23-8c2b-a22b44d6984c">

<img width="1871" alt="image" src="https://github.com/pendulum-chain/spacewalk/assets/6690623/daacc3a7-a654-439a-ac94-e0b23a8eafa6">

**Comment by ebma** [comment]
@zoveress to facilitate the investigation of this ticket, can we change the log level of one of the Spacewalk clients to 'DEBUG'? Doesn't matter which one on Amplitude or Pendulum as they all seem to have the same issue at the same time (at least when it occurs for which we don't know the reason yet).

**Comment by ebma** [comment]
@pendulum-chain/product this is a bug that can lead to the vault client being unresponsive and only able to bridge after the next periodic restart. It does not occur frequently and we first have to monitor the instances when this is happening.

**Comment by b-yap** [comment]
From the `#DevOps Incidents`, it started as far back as Sept 17, 2023.


extra: `Memory Usage High` alerts happened on Sept 21, 2023

**Comment by vadaynujra** [comment]
@annatekl anything blocking this from being moved to Ready?

**Comment by annatekl** [comment]
moved @vadaynujra

**Comment by ebma** [comment]
@b-yap please don't forget to assign yourself to tickets once you start working on them so that others don't. 😬

**Comment by b-yap** [comment]
@ebma noted. 

Question; as this has something to do with the vaults, should we move this ticket over there?

**Comment by ebma** [comment]
Over where? It's already in the spacewalk repository or would you prefer to have it elsewhere? 😅

**Comment by b-yap** [comment]
ah nevermind, I got confused with the zenhub "Pendulum" icon  :weary:
