### ISSUE TITLE
Make vault client retry submissions for RPC timeout errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#516]
## Context

Sometimes, our RPC nodes are slow or unresponsive and it happens that transaction submissions time out because of this error. The vault client currently does not retry the submission of the transaction for those errors, but it should.

<img width="1715" alt="image" src="https://github.com/pendulum-chain/spacewalk/assets/6690623/88eb68f7-09fc-4fd8-aa8f-0e7eb9b3c946">

## TODO

Make the vault client retry the submission of extrinsics for timeout errors thrown by the RPC client.

**Comment by ebma** [comment]
@pendulum-chain/product this feature will prevent users from having to wait hours for the execution of bridging requests even if our RPC nodes are slow.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/516?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
