### ISSUE TITLE
Test Case `stellar_overlay_should_receive_scp_messages` fails 

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/spacewalk#520]
This test case:
https://github.com/pendulum-chain/spacewalk/blob/ea66a3062e6edf05a4ed7b377f107e1f95b688f1/clients/stellar-relay-lib/src/tests/mod.rs#L42-L67

failed twice:
```
failures:

---- tests::stellar_overlay_should_receive_scp_messages stdout ----
thread 'tests::stellar_overlay_should_receive_scp_messages' panicked at clients/stellar-relay-lib/src/tests/mod.rs:66:5:
assertion failed: !scps_vec.lock().await.is_empty()
```
See
https://github.com/pendulum-chain/spacewalk/actions/runs/8980428758/job/24674454969?pr=513#step:12:510
https://github.com/pendulum-chain/spacewalk/actions/runs/8980428758/job/24672556732?pr=513#step:12:509

Investigate whether the test case only needs an update, or [an update of the config file](https://github.com/pendulum-chain/spacewalk/tree/main/clients/stellar-relay-lib/resources/config/testnet) is required.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/520?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
I see that this test [works](https://github.com/pendulum-chain/spacewalk/actions/runs/10287207285/job/28523428666?pr=546#step:13:507) at least in the latest runs. Maybe it was solved by changing the config file?

**Comment by bogdanS98** [comment]
@gianfra-t There was at least one config file change in the last 2 months (e.g. [this](https://github.com/pendulum-chain/spacewalk/commit/524b15e10866dee855a9b2c4d0a930702124b59b)) and this ticket's description was last updated on May 7th which is way before that. I also think this is solved already by the new config file changes.

**Comment by ebma** [comment]
Would be great if this got fixed automatically. @gianfra-t did you notice the test case failing in any of your comments of the https://github.com/pendulum-chain/spacewalk/pull/550 PR? If that's not the case I would be confident enough to close this ticket.

**Comment by gianfra-t** [comment]
Actually, no. Latest tests are failing due to format [issues](https://github.com/pendulum-chain/spacewalk/actions/runs/10575876846/job/29300486478?pr=550), or random compilation issues. So I think it is fixed.

**Comment by b-yap** [comment]
I agree.
