### ISSUE TITLE
Make issue pallet benchmarks run successfully on Pendulum runtimes

### ISSUE THREAD

**Issue by bogdanS98** [pendulum-chain/spacewalk#528]
### Context

The problem is that on the testchain runtime, we are defining the relay chain currency ID for the griefing collateral, see [here](https://github.com/pendulum-chain/spacewalk/blob/8331813b819601511d885f727cd0ccc71dab0e66/testchain/runtime/testnet/src/lib.rs#L377). On our actual production runtimes we use the native currency. Since [these](https://github.com/pendulum-chain/spacewalk/blob/8331813b819601511d885f727cd0ccc71dab0e66/pallets/issue/src/benchmarking.rs#L72-L74) calls only mint the 'collateral token' into the accounts used for benchmarking and not the native token, the call to `requestIssue()` fails to lock the griefing collateral in the native currency.
As we want to keep having the griefing collateral denoted in the native currency, we should change the benchmark logic so that also the 'griefing collateral currency' token is minted [here](https://github.com/pendulum-chain/spacewalk/blob/8331813b819601511d885f727cd0ccc71dab0e66/pallets/issue/src/benchmarking.rs#L72-L74).

In addition to this, we should have the amount used in the benchmark [here](https://github.com/pendulum-chain/spacewalk/blob/8331813b819601511d885f727cd0ccc71dab0e66/pallets/issue/src/benchmarking.rs#L64) match the 'minimum transfer amount' [here](https://github.com/pendulum-chain/pendulum/blob/7e444dd942fcdff81ba3edd619e3347fdd8a79ad/node/src/chain_spec.rs#L608) so that we don't get `AmountBelowMinimumTransferAmount` error when running the benchmarks.

### Requirement

Provide fixes for all of the above and re-run benchmarks for `issue` pallet on Spacewalk

**Comment by ebma** [comment]
> In addition to this, we should have the amount used in the benchmark [here](https://github.com/pendulum-chain/spacewalk/blob/8331813b819601511d885f727cd0ccc71dab0e66/pallets/issue/src/benchmarking.rs#L64) match the 'minimum transfer amount' [here](https://github.com/pendulum-chain/pendulum/blob/7e444dd942fcdff81ba3edd619e3347fdd8a79ad/node/src/chain_spec.rs#L608) so that we don't get AmountBelowMinimumTransferAmount error when running the benchmarks.

Might make sense to also check if we can/should add the same improvement to other pallets ie. redeem and replace @bogdanS98.
