### ISSUE TITLE
add stellar-relay pallet to runtime

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/spacewalk#58]
You'll have to add the following to the construct_runtime! macro in the runtime:
```
StellarRelay: stellar_relay::{Pallet, Call, Config<T>, Storage, Event<T>}
```
And the following config:
```
impl stellar_relay::Config for Runtime {
    type Event = Event;
    type WeightInfo = ();
    type ParachainBlocksPerBitcoinBlock = ParachainBlocksPerBitcoinBlock;
}
```
And make sure it compiles.

Refer to this file as a guide: https://github.com/interlay/interbtc/blob/master/standalone/runtime/src/lib.rs
(Note in this reference it will be called BTCRelay)

**Comment by ebma** [comment]
Closing this because it was done in #99.
