### ISSUE TITLE
Allow for destination address on `report_stellar_transaction` and `redeem`

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/spacewalk#68]
**Incentive**
We support bridging assets from Stellar (which uses `ed25119`), and for ease of use, we want to also allow users to be able to connect an external wallet to the chain using spacewalk. 
Most wallets ([polkadot.js](https://polkadot.js.org/extension/) and [Talisman](https://talisman.xyz/)), unfortunately don't let you chose the `ed25519` scheme, and only import/create accounts using the `sr25519` scheme.

**Problem**
So far, we derive the address from the Stellar public key from the incoming transaction's envelope XDR. We take this from the sender of the payment, and this public key will always be `ed25519`, and we cannot derive the `sr25519` version from it.

**What is required**
Changing the signature of methods `report_stellar_transaction` and `redeem` to be able to specify a destination address in both ways.
So the funds can go from the `ed25519` version of the address in Stellar, to the `sr25519` version in Pendulum.

**Comment by ebma** [comment]
Closing this because it does not apply with the latest version of spacewalk anymore. (We don't derive the destination address).
