### ISSUE TITLE
SBP: Redeem #2

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/spacewalk#80]
Before withdrawing, It should check first if the provided `stellar_vault_pubkey` has enough balance to be withdrawn too. If the Vault doesn’t have enough funds, the user will lose their funds in Pendulum and will never receive them in Stellar.

Allowing users to provide any `stellar_vault_pubkey` could lead to malicious users draining others Vaults as long as those have enough balance.
    
I miss a registry, a mapping between accounts and vaults pubkeys that whitelists what users can withdraw from a certain Vault.

**Comment by TorstenStueber** [comment]
The flow as it is implemented right not will change greatly in the next couple of weeks while we are working on the [2nd milestone of the web3 grant for Spacewalk](https://github.com/w3f/Grants-Program/blob/master/applications/spacewalk-bridge.md#milestone-2--multi-asset-collateral-management).

I will keep this ticket open and address it once the new flow is implemented.

**Comment by ebma** [comment]
Changing this because the structure of the redeem changed and this does not apply anymore.
