### ISSUE TITLE
SBP: Add benchmarks to Spacewalk pallet

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/spacewalk#81]

**Comment by TorstenStueber** [comment]
Thanks for your comment, we will address this in a few weeks after we implented the [2nd milestone of the web3 grant for Spacewalk](https://github.com/w3f/Grants-Program/blob/master/applications/spacewalk-bridge.md#milestone-2--multi-asset-collateral-management).

**Comment by ebma** [comment]
Closing because we now added benchmarks to all the spacewalk-related pallets with extrinsics.
