### ISSUE TITLE
SBP: Readme enhancement

### ISSUE THREAD

**Issue by NachoPal** [pendulum-chain/spacewalk#82]
It would be very useful if you add a diagram to visualise the Spacewalk Deposit/Redeem flow in the README.md (probably you can take it from the W3f grant documentation)

**Comment by TorstenStueber** [comment]
Hey @NachoPal thanks for this suggestion. The flow as it is implemented right not will change greatly in the next couple of weeks while we are working on the [2nd milestone of the web3 grant for Spacewalk](https://github.com/w3f/Grants-Program/blob/master/applications/spacewalk-bridge.md#milestone-2--multi-asset-collateral-management).

We will update and improve the documentation once that change is implemented.

**Comment by vadaynujra** [comment]
Add:

- Commands for building
- Running testnet
- Links to guide documentation

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/82?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
@vadaynujra [your comment](https://github.com/pendulum-chain/spacewalk/issues/82#issuecomment-1490210210) is not clear to me. Does that apply to the README or our official docs?

**Comment by vadaynujra** [comment]
You tell me @TorstenStueber and if you can't, it might be a question for Nacho. 
- do we need to do this in the short term?
- where does it need to be stored? 

Also bringing in @ebma for input.

**Comment by TorstenStueber** [comment]
I think we can close this issue as this was from the review of milestone 3. It is not relevant anymore. We should improve docs but that is a different story.

**Comment by prayagd** [comment]
Closing this as per above comment.
