### ISSUE TITLE
Listen to and execute issue events in vault client

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#86]
Requires #85. 

Make the vault client listen to events related to issue requests, emitted by the connected parachain and execute them if they are directed at them.

### Handling Issue events
- On a new `RequestIssueEvent` check if it targets this vault and if it does, store it as a new `Issue` request locally in a set
- On a new `CancelIssueEvent` or `ExecuteIssueEvent` remove the related `Issue` if it is contained in the local set
- In a separate task, sequentially try to execute all the issues contained in the issue set (described in more detail below)

### Storing Stellar transactions directed at the vault
- When issuing, the user has to send a Stellar transaction with a payment to the vault
- The vault continuously fetches the transactions for its Stellar account from the network and stores them locally
    - It would be okay to only store the new transactions after going online
    - It would also be okay to discard all transactions that don't contain a transaction memo, because the memo is required for fulfilling issue requests

### Executing Issue requests
- First, look through the stored (vault-related) Stellar transactions and try to find one that contains the `issue_id` as a transaction memo
    - If no such transaction can be found, skip the issue for now (or remove it from the set? to be defined) 
- Check if the `amount` and `asset` contained in the `Issue` match `amount` and `asset` contained in the Stellar transaction
    - If they don't match, print an error and remove the issue from the set 
- If they match, build the proof
    - Look at the Stellar transactions `ledger` field and retrieve the `externalizedMessages[]` and `transactionSet[]` from the map (built in #85)
    - (Optional: Reduce the externalized messages to a minimal amount that builds a valid quorum set (11-12 nodes) and check all the messages for validity, i.e. check their signatures, if they all contain the same txSetHash, etc.)
    - Call the `executeIssue()` extrinsic with the Stellar transaction, the externalized messages, and the transaction set

**Comment by b-yap** [comment]
@ebma 
> On a new CancelIssueEvent or ExecuteIssueEvent remove the related Issue if it is contained in the local set
In a separate task, sequentially try to execute all the issues contained in the issue set (described in more detail below)

Uhm, when do I actually  "execute"? 
After receiving an `ExecuteIssueEvent`, or a spawned task that will go over the `RequestIssueEvent` set?

**Comment by b-yap** [comment]
done by https://github.com/pendulum-chain/spacewalk/pull/146
