### ISSUE TITLE
Listen to and execute redeem events in vault client

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#87]
Requires #85. 

Make the vault client listen to events related to redeem requests, emitted by the connected parachain and execute them if they are directed at them.

### Executing Redeem requests
- On receiving a new `RequestRedeemEvent`, check if it targets this vault. If it does not, ignore the request
- Create and submit a Stellar transaction for the redeem (as described below)
- Build the proof
    - Use the `ledger` field of the submitted Stellar transaction to retrieve the relevant externalized messages and transaction set from #85 
        - maybe to get the `ledger` field, the transaction has to be fetched back from the network because when creating it locally the `ledger` field is probably empty
- Call the `execute_redeem()` extrinsic of the redeem pallet with the Stellar transaction, the externalized messages, and the transaction set 

### Creating the redeem transaction for Stellar
- When redeeming, the user specifies a `stellar_address`, `amount` and `asset`, determining how and where he wants the vault  to send the redeemed funds to
- The vault then has to create and submit a Stellar transaction that fulfills these criteria **and includes the `redeem_id` of the respective `Redeem` request as the transaction memo**

**Comment by b-yap** [comment]
completed: https://github.com/pendulum-chain/spacewalk/pull/148
