### ISSUE TITLE
Create 'currency' pallet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#91]
We should extend the functionalities offered by the `orml_tokens` pallet. The 'currency' pallet will be tightly coupled to the `orml_tokens` pallet. 

The currency pallet should offer:
- getters for the native, relay-chain, and wrapped currency ID
- a struct that can hold an amount and currency ID, and offers fixed point arithmetic for increased precision. It might also be useful to add helper functions e.g. for transferring and minting, to this struct

Should be pretty similar to [this](https://github.com/interlay/interbtc/tree/master/crates/currency/src) pallet.

**Comment by ashneverdawn** [comment]
Note: we decided to use `Fungibles` trait instead of `MultiCurrency`, so any chain not using `orml_tokens` could still add spacewalk as well.

**Comment by ashneverdawn** [comment]
switching from `MultiCurrency` to `Fungibles` will be done with this ticket: https://github.com/pendulum-chain/spacewalk/issues/124

**Comment by gonzamontiel** [comment]
Closing since https://github.com/pendulum-chain/spacewalk/pull/123 was merged.
