### ISSUE TITLE
Implement smart pruning mechanism for stored SCP messages in oracle agent

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#95]
We should have an intelligent mechanism to prune the SCP messages from the oracle agent. This way, we save storage space and increase the speed of lookups.
This is not a trivial task, because it is not easy to identify whether SCP messages can already be dropped.

Some metrics we can use to identify entries that can be dropped:
- If all transactions in the transaction set belonging to the SCP messages of a certain slot do not have any transaction memo, (or it is not of the MEMO_HASH type with the correct length), we can drop the SCP messages for that slot since these transactions cannot be related to spacewalk (or if they are, they are faulty). 
- ~Assuming the oracle agent has the list of open issue/redeem requests, it can check whether the ID of one of these requests is included in any of the transactions in a transaction set. If this is not the case, the SCP messages for that transaction set can be dropped. **BUT** it could happen that due to high latency, a transaction is first externalized on Stellar, whereas the issue/redeem request was not created yet. So here we would need some kind of delayed check to prevent this race condition.~ This is too risky on race conditions/bad timing probably.
- SCP messages for transactions that are 'older' than the issue/redeem periods of the respective pallets allow can also be dropped. Assuming that the parachain status is 'running' and is not stalled due to an error

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/95?planning-poker) with Zenhub @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
@ebma is this ticket urgent or merely a nice to have right now? Do we already see too much memory usage or slow down?

Isn't there a definite way that any SCP message from a slot a certain number away from the current slot does definitely have no use anymore (a few days probably)? This your last point, correct?

In that case I think that this would be optimization enough and there would always just be fairly a limited number of SCP messages in memory/under consideration.

**Comment by ebma** [comment]
It's really not urgent. As you can see I originally created the ticket half a year ago already, and at the time it was relevant because it was obvious that we could strip that down a little.
But now that we solved #309 it's probably not really necessary to have this smart pruning, I assume the memory we save doing so is not that significant.

**Comment by TorstenStueber** [comment]
Okay, maybe we close this ticket for now? We can record it at another place (e.g., Future Proposals) and reopen any time when necessary. This way we keep the backlog clean.

**Comment by ebma** [comment]
Sure, I don't mind. Can you do that @TorstenStueber?

**Comment by TorstenStueber** [comment]
Yes, I will.
